
PROGRAM _INIT
	//AID
	HMI_AID_Loading;
	
	//ALR - Alarm
	HMI_ALR_Loading;
	
	//BTC - Bottles Bottom Cooling
	HMI_BTC_Loading;
	
	//CAP - Capper
	HMI_CAP_Loading;
	
	//CRW - Crowner
	HMI_CRW_Loading;
	
	// CO - Change Over
	HMI_CO_Loading;
	
	//COP - Cleaning out place
	HMI_COP_Loading;

	//CSR - Container Size Regulation
	HMI_CSR_Loading;
	
	//DMC - Dummy containers
	HMI_DMC_Loading;
	
	//GNS - General safety
	HMI_GNS_Loading;
	
	//MAU - Machine auxiliary
	HMI_MAU_Loading;
	
	//MNM - Main drive
	HMI_MNM_Loading;

	//MNT - Maintenance
	HMI_MNT_Loading;
	
	//ICO - Intelli Change Over
	HMI_ICO_Loading;
	
	//ITC - Interchange
	HMI_ITC_Loading;
	
	//OPS - Operator safety
	HMI_OPS_Loading;
	
	//HMI - Option Page
	HMI_OPT_Loading;
	
	//PAO - HMI PAO Page
	HMI_PAO_Loading;
	
	//RNS - RINSER
	HMI_RNS_Loading;
	
	//SFT - SHIFT REGISTER
	HMI_SFT_Loading;
	
	//TNK - Tank
	HMI_TNK_Loading;
	
	//Device (Valves - Instruments - Pumps)
	HMI_Valves_Loading;
	HMI_Instruments_Loading;
	HMI_Pumps_Loading;
	
	//HMI Variables
	HMI_Variables_Loading;
	
	HMI_CounterInit;
END_PROGRAM