ACTION DOS_Hardware_CFG: 
	(***** VALVES *****)
	AVJ[201].IN_ConfigPresent				:= TRUE;
	AVJ[201].IN_ConfigType 					:= 0;
	AVJ[201].IN_Simulation 					:= FALSE;
	AVJ[201].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[201].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[201].IN_StrokeTime 					:= T#5s;

	AVJ[210].IN_ConfigPresent				:= TRUE;
	AVJ[210].IN_ConfigType 					:= 0;
	AVJ[210].IN_Simulation 					:= FALSE;
	AVJ[210].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[210].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[210].IN_StrokeTime 					:= T#5s;

	AVJ[211].IN_ConfigPresent				:= TRUE;
	AVJ[211].IN_ConfigType 					:= 0;
	AVJ[211].IN_Simulation 					:= FALSE;
	AVJ[211].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[211].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[211].IN_StrokeTime 					:= T#5s;
	
	AVJ[212].IN_ConfigPresent				:= FALSE;
	AVJ[212].IN_ConfigType 					:= 0;
	AVJ[212].IN_Simulation 					:= FALSE;
	AVJ[212].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[212].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[212].IN_StrokeTime 					:= T#5s;
	
	AVJ[215].IN_ConfigPresent				:= TRUE;
	AVJ[215].IN_ConfigType 					:= 0;
	AVJ[215].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[215].IN_Simulation 					:= FALSE;
	AVJ[215].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[215].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[215].IN_StrokeTime 					:= T#5s;
	
	AVJ[216].IN_ConfigPresent				:= TRUE;
	AVJ[216].IN_ConfigType 					:= 0;
	AVJ[216].IN_Simulation 					:= FALSE;
	AVJ[216].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[216].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[216].IN_StrokeTime 					:= T#5s;
	
	AVJ[217].IN_ConfigPresent				:= TRUE;
	AVJ[217].IN_ConfigType 					:= 0;
	AVJ[217].IN_Simulation 					:= FALSE;
	AVJ[217].IN_ConfigPositionSensorOpened 	:= FALSE;
	AVJ[217].IN_ConfigPositionSensorClosed 	:= FALSE;
	AVJ[217].IN_StrokeTime 					:= T#5s;
	
	AVJ[218].IN_ConfigPresent				:= FALSE;
	AVJ[218].IN_ConfigType 					:= 0;
	AVJ[218].IN_Simulation 					:= FALSE;
	AVJ[218].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[218].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[218].IN_StrokeTime 					:= T#5s;
	
	AVJ[221].IN_ConfigPresent				:= FALSE;
	AVJ[221].IN_ConfigType 					:= 0;
	AVJ[221].IN_ConfigNormallyOpen			:= TRUE;
	AVJ[221].IN_Simulation 					:= FALSE;
	AVJ[221].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[221].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[221].IN_StrokeTime 					:= T#5s;
	
	AVJ[230].IN_ConfigPresent				:= CFG_Par.Doser.RecoverySkid;
	AVJ[230].IN_ConfigType 					:= 0;
	AVJ[230].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[230].IN_Simulation 					:= FALSE;
	AVJ[230].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[230].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[230].IN_StrokeTime 					:= T#5s;

	AVJ[231].IN_ConfigPresent				:= CFG_Par.Doser.RecoverySkid;
	AVJ[231].IN_ConfigType 					:= 0;
	AVJ[231].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[231].IN_Simulation 					:= FALSE;
	AVJ[231].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[231].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[231].IN_StrokeTime 					:= T#5s;

	AVJ[232].IN_ConfigPresent				:= CFG_Par.Doser.RecoverySkid;
	AVJ[232].IN_ConfigType 					:= 0;
	AVJ[232].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[232].IN_Simulation 					:= FALSE;
	AVJ[232].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[232].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[232].IN_StrokeTime 					:= T#5s;

	AVJ[233].IN_ConfigPresent				:= CFG_Par.Doser.RecoverySkid;
	AVJ[233].IN_ConfigType 					:= 0;
	AVJ[233].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[233].IN_Simulation 					:= FALSE;
	AVJ[233].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[233].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[233].IN_StrokeTime 					:= T#5s;

	AVJ[234].IN_ConfigPresent				:= CFG_Par.Doser.RecoverySkid;
	AVJ[234].IN_ConfigType 					:= 0;
	AVJ[234].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[234].IN_Simulation 					:= FALSE;
	AVJ[234].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[234].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[234].IN_StrokeTime 					:= T#5s;

	AVJ[235].IN_ConfigPresent				:= CFG_Par.Doser.RecoverySkid;
	AVJ[235].IN_ConfigType 					:= 0;
	AVJ[235].IN_ConfigNormallyOpen			:= FALSE;
	AVJ[235].IN_Simulation 					:= FALSE;
	AVJ[235].IN_ConfigPositionSensorOpened 	:= TRUE;
	AVJ[235].IN_ConfigPositionSensorClosed 	:= TRUE;
	AVJ[235].IN_StrokeTime 					:= T#5s;

	
	RVJ[201].IN_ConfigPresent 				:= FALSE;
	RVJ[201].IN_Simulation 					:= FALSE; 
	RVJ[201].IN_ConfigPositionSensorOpened 	:= FALSE; 
	RVJ[201].IN_ConfigPositionSensorClosed 	:= FALSE; 
	RVJ[201].IN_ConfigPositionAnalogFBK 	:= FALSE; 
	RVJ[201].IN_StrokeTime 					:= t#3s;
	RVJ[201].IN_ConfigNormallyOpen 			:= FALSE;
	
	(***** MOTORS *****)
	PPJ[202].IN_ConfigPresent				:= CFG_Par.Doser.Present;
	PPJ[202].IN_Reverse						:= FALSE;
	PPJ[202].IN_ManEn						:= TRUE;
	PPJ[202].IN_FrequencyMin				:= 0.0;
	PPJ[202].IN_FrequencyMax				:= 60.0;
	
	PPJ203.IN_ConfigPresent					:= FALSE; 
	PPJ203.IN_ManEn							:= TRUE;
	PPJ203.IN_Simulation 					:= FALSE;

	MMJ[201].IN_ConfigPresent				:= CFG_Par.Doser.Present;
	MMJ[201].IN_Reverse						:= FALSE;
	MMJ[201].IN_ManEn						:= TRUE;
	MMJ[202].IN_FrequencyMin				:= 0.0;
	MMJ[202].IN_FrequencyMax				:= 100.0;
	
	MMF[205].IN_ConfigPresent				:= CFG_Par.Doser.Present;
	MMF[205].IN_ManEn						:= TRUE;
	MMF[205].IN_FrequencyMin				:= 0.0;
	MMF[205].IN_FrequencyMax				:= 60.0;
	
	MMF[206].IN_ConfigPresent				:= CFG_Par.Doser.Present;
	MMF[206].IN_ManEn						:= TRUE;
	MMF[206].IN_FrequencyMin				:= 0.0;
	MMF[206].IN_FrequencyMax				:= 60.0;
	
	(***** ANALOG *****)
	LTJ[203].IN_ConfigPresent				:= CFG_Par.Doser.Present;
	LTJ[203].IN_Simulation					:= FALSE;
	LTJ[203].IN_0_20mA						:= TRUE;
	LTJ[203].IN_ScaleLOW					:= 0;
	LTJ[203].IN_ScaleHIGH					:= 100; //%
	LTJ[203].IN_MaskEn						:= TRUE;
	LTJ[203].IN_ConfigPopup					:= TRUE;
	LTJ[203].IN_CompareMode					:= VAR_DOS_SEQ.Device.LTJ203.CMP;

	TTJ[203].IN_ConfigPresent				:= CFG_Par.Doser.Present;
	TTJ[203].IN_Simulation					:= FALSE;
	TTJ[203].IN_0_20mA						:= TRUE;
	TTJ[203].IN_ScaleLOW					:= 0.0;
	TTJ[203].IN_ScaleHIGH					:= 100.0;
	TTJ[203].IN_MaskEn						:= TRUE;
	TTJ[203].IN_ConfigPopup					:= TRUE;
	TTJ[203].IN_CompareMode					:= VAR_DOS_SEQ.Device.TTJ203.CMP;
	
	_210PTF.IN_ConfigPresent 				:= CFG_Par.Doser.Present;
	_210PTF.IN_OffDelay;
	_210PTF.IN_OnDelay;
	
	//FILIPPO
	_205MEF.IN_ConfigPresent					:= TRUE;
	_205MEF.IN_Simulation						:= FALSE;
	_205MEF.IN_0_20mA							:= TRUE;
	_205MEF.IN_ScaleLOW							:= 0.0;
	_205MEF.IN_ScaleHIGH						:= 680.0; //Probe Lenght datasheet
	_205MEF.IN_AlarmEn							:= TRUE;
	_205MEF.IN_MinDev							:= 1.0; //[mm]
	_205MEF.IN_MaxDev							:= 1.0; //[mm]
	_205MEF.IN_WaitDelay						:= t#100ms;
	_205MEF.IN_HighLimitEn						:= TRUE;
	_205MEF.IN_HighLimitSP						:= 200.0;
	_205MEF.IN_HighLimitHyst					:= 0.0 ;
	_205MEF.IN_HighLimitDelay					:= t#100ms;
	_205MEF.IN_LowLimitEn						:= TRUE;
	_205MEF.IN_LowLimitSP						:= 8.0;
	_205MEF.IN_LowLimitHyst						:= 0.0;
	_205MEF.IN_LowLimitDelay					:= t#100ms;
	_205MEF.IN_Direct_Inverse					:= TRUE; //FALSE = Direct - TRUE = Inverse
	//_205MEF.IN_Delta							:= -308.0; //[mm] Delta Value for Real Component Height (always added to the Probe Value) To define in test with ADJ
		
	//_206MEF
	_206MEF.IN_ConfigPresent					:= TRUE;
	_206MEF.IN_Simulation						:= FALSE;
	_206MEF.IN_0_20mA							:= TRUE;
	_206MEF.IN_ScaleLOW							:= 0.0;
	_206MEF.IN_ScaleHIGH						:= 680.0; //Probe Lenght datasheet
	_206MEF.IN_AlarmEn							:= TRUE;
	_206MEF.IN_MinDev							:= 1.0; //[mm]
	_206MEF.IN_MaxDev							:= 1.0; //[mm]
	_206MEF.IN_WaitDelay						:= t#100ms;
	_206MEF.IN_HighLimitEn						:= TRUE;
	_206MEF.IN_HighLimitSP						:= 200.0;
	_206MEF.IN_HighLimitHyst					:= 0.0 ;
	_206MEF.IN_HighLimitDelay					:= t#100ms;
	_206MEF.IN_LowLimitEn						:= TRUE;
	_206MEF.IN_LowLimitSP						:= 8.0;
	_206MEF.IN_LowLimitHyst						:= 0.0;
	_206MEF.IN_LowLimitDelay					:= t#100ms;
	_206MEF.IN_Direct_Inverse					:= TRUE; //FALSE = Direct - TRUE = Inverse
	//_206MEF.IN_Delta							:= -310.0; //[mm] Delta Value for Real Component Height (always added to the Probe Value) To define in test with ADJ
	
	(***** DIGITAL *****) //FILIPPO
	_215DSF.IN_ConfigPresent 					:= TRUE;
	_216DSF.IN_ConfigPresent 					:= TRUE;
	_217DSF.IN_ConfigPresent 					:= TRUE;
	_210DSX.IN_ConfigPresent 					:= TRUE;
	_211DSX.IN_ConfigPresent 					:= TRUE;
	
	_212DSF.IN_ConfigPresent 					:= TRUE;
	_213DSF.IN_ConfigPresent 					:= TRUE;
	
	_211CPF.IN_ConfigPresent					:= TRUE;
	
	LSJ200L.IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	LSJ200M.IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	LSJ200H.IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	LSJ[201].IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	LSJ[202].IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	FSJ[201].IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	FSJ[202].IN_ConfigPresent					:= CFG_Par.Doser.RecoverySkid;
	
END_ACTION
