(*HMI_PAM_B1 Database for Filler PLC*)
(*Author = ????*)
(*DB Version : 0.00*)
(*File Version : 3,17*)

TYPE
        HMI_PAM_B1_Type:    STRUCT
                            _000 : REAL; (*Device B - PPB201 - OUT Min [Hz]*)
                            _001 : REAL; (*Device B - PPB201 - OUT Max [Hz]*)
                            _002 : REAL; (*Device B - PPB201 - Spare *)
                            _003 : REAL; (*Device B - PPB201 - Spare *)
                            _004 : REAL; (*Device B - PPB201 - Spare *)
                            _005 : REAL; (*Device B - PPB202 - OUT Min [Hz]*)
                            _006 : REAL; (*Device B - PPB202 - OUT Max [Hz]*)
                            _007 : REAL; (*Device B - PPB202 - Spare *)
                            _008 : REAL; (*Device B - PPB202 - Spare *)
                            _009 : REAL; (*Device B - PPB202 - Spare *)
                            _010 : REAL; (*Device B - PPB203 - OUT Min [Hz]*)
                            _011 : REAL; (*Device B - PPB203 - OUT Max [Hz]*)
                            _012 : REAL; (*Device B - PPB203 - Spare *)
                            _013 : REAL; (*Device B - PPB203 - Spare *)
                            _014 : REAL; (*Device B - PPB203 - Spare *)
                            _015 : REAL; (*Device B - PPB204 - OUT Min [Hz]*)
                            _016 : REAL; (*Device B - PPB204 - OUT Max [Hz]*)
                            _017 : REAL; (*Device B - PPB204 - Spare *)
                            _018 : REAL; (*Device B - PPB204 - Spare *)
                            _019 : REAL; (*Device B - PPB204 - Spare *)
                            _020 : REAL; (*Device B - PPB205 - OUT Min [Hz]*)
                            _021 : REAL; (*Device B - PPB205 - OUT Max [Hz]*)
                            _022 : REAL; (*Device B - PPB205 - Spare *)
                            _023 : REAL; (*Device B - PPB205 - Spare *)
                            _024 : REAL; (*Device B - PPB205 - Spare *)
                            _025 : REAL; (*Device B - PPB206 - OUT Min [Hz]*)
                            _026 : REAL; (*Device B - PPB206 - OUT Max [Hz]*)
                            _027 : REAL; (*Device B - PPB206 - Spare *)
                            _028 : REAL; (*Device B - PPB206 - Spare *)
                            _029 : REAL; (*Device B - PPB206 - Spare *)
                            _030 : REAL; (*Device B - PPB207 - OUT Min [Hz]*)
                            _031 : REAL; (*Device B - PPB207 - OUT Max [Hz]*)
                            _032 : REAL; (*Device B - PPB207 - Spare *)
                            _033 : REAL; (*Device B - PPB207 - Spare *)
                            _034 : REAL; (*Device B - PPB207 - Spare *)
                            _035 : REAL; (*Device B - PPB208 - OUT Min [Hz]*)
                            _036 : REAL; (*Device B - PPB208 - OUT Max [Hz]*)
                            _037 : REAL; (*Device B - PPB208 - Spare *)
                            _038 : REAL; (*Device B - PPB208 - Spare *)
                            _039 : REAL; (*Device B - PPB208 - Spare *)
                            _040 : REAL; (*Device B - PPB209 - OUT Min [Hz]*)
                            _041 : REAL; (*Device B - PPB209 - OUT Max [Hz]*)
                            _042 : REAL; (*Device B - PPB209 - Spare *)
                            _043 : REAL; (*Device B - PPB209 - Spare *)
                            _044 : REAL; (*Device B - PPB209 - Spare *)
                            _045 : REAL; (*Device B - PPB220 - OUT Min [Hz]*)
                            _046 : REAL; (*Device B - PPB220 - OUT Max [Hz]*)
                            _047 : REAL; (*Device B - PPB220 - Spare *)
                            _048 : REAL; (*Device B - PPB220 - Spare *)
                            _049 : REAL; (*Device B - PPB220 - Spare *)
                            _050 : REAL; (*Device B - PPB212 - OUT Min [Hz]*)
                            _051 : REAL; (*Device B - PPB212 - OUT Max [Hz]*)
                            _052 : REAL; (*Device B - PPB212 - Spare *)
                            _053 : REAL; (*Device B - PPB212 - Spare *)
                            _054 : REAL; (*Device B - PPB212 - Spare *)
                            _055 : REAL; (*Device B - Spare *)
                            _056 : REAL; (*Device B - Spare *)
                            _057 : REAL; (*Device B - Spare *)
                            _058 : REAL; (*Device B - Spare *)
                            _059 : REAL; (*Device B - Spare *)
                            _060 : REAL; (*Device B - Spare *)
                            _061 : REAL; (*Device B - Spare *)
                            _062 : REAL; (*Device B - Spare *)
                            _063 : REAL; (*Device B - Spare *)
                            _064 : REAL; (*Device B - Spare *)
                            _065 : REAL; (*Device B - Spare *)
                            _066 : REAL; (*Device B - Spare *)
                            _067 : REAL; (*Device B - Spare *)
                            _068 : REAL; (*Device B - Spare *)
                            _069 : REAL; (*Device B - Spare *)
                            _070 : REAL; (*Device B - Spare *)
                            _071 : REAL; (*Device B - Spare *)
                            _072 : REAL; (*Device B - Spare *)
                            _073 : REAL; (*Device B - Spare *)
                            _074 : REAL; (*Device B - Spare *)
                            _075 : REAL; (*Device B - Spare *)
                            _076 : REAL; (*Device B - Spare *)
                            _077 : REAL; (*Device B - Spare *)
                            _078 : REAL; (*Device B - Spare *)
                            _079 : REAL; (*Device B - Spare *)
                            _080 : REAL; (*Device B - Spare *)
                            _081 : REAL; (*Device B - Spare *)
                            _082 : REAL; (*Device B - Spare *)
                            _083 : REAL; (*Device B - Spare *)
                            _084 : REAL; (*Device B - Spare *)
                            _085 : REAL; (*Device B - Spare *)
                            _086 : REAL; (*Device B - Spare *)
                            _087 : REAL; (*Device B - Spare *)
                            _088 : REAL; (*Device B - Spare *)
                            _089 : REAL; (*Device B - Spare *)
                            _090 : REAL; (*Device B - Spare *)
                            _091 : REAL; (*Device B - Spare *)
                            _092 : REAL; (*Device B - Spare *)
                            _093 : REAL; (*Device B - Spare *)
                            _094 : REAL; (*Device B - Spare *)
                            _095 : REAL; (*Device B - Spare *)
                            _096 : REAL; (*Device B - Spare *)
                            _097 : REAL; (*Device B - Spare *)
                            _098 : REAL; (*Device B - Spare *)
                            _099 : REAL; (*Device B - Spare *)
                            _100 : REAL; (*Device F - Spare *)
                            _101 : REAL; (*Device F - Spare *)
                            _102 : REAL; (*Device F - Spare *)
                            _103 : REAL; (*Device F - Spare *)
                            _104 : REAL; (*Device F - Spare *)
                            _105 : REAL; (*Device F - Spare *)
                            _106 : REAL; (*Device F - Spare *)
                            _107 : REAL; (*Device F - Spare *)
                            _108 : REAL; (*Device F - Spare *)
                            _109 : REAL; (*Device F - Spare *)
                            _110 : REAL; (*Device F - Spare *)
                            _111 : REAL; (*Device F - Spare *)
                            _112 : REAL; (*Device F - Spare *)
                            _113 : REAL; (*Device F - Spare *)
                            _114 : REAL; (*Device F - Spare *)
                            _115 : REAL; (*Device F - Spare *)
                            _116 : REAL; (*Device F - Spare *)
                            _117 : REAL; (*Device F - Spare *)
                            _118 : REAL; (*Device F - Spare *)
                            _119 : REAL; (*Device F - Spare *)
                            _120 : REAL; (*Device F - Spare *)
                            _121 : REAL; (*Device F - Spare *)
                            _122 : REAL; (*Device F - Spare *)
                            _123 : REAL; (*Device F - Spare *)
                            _124 : REAL; (*Device F - Spare *)
                            _125 : REAL; (*Device F - Spare *)
                            _126 : REAL; (*Device F - Spare *)
                            _127 : REAL; (*Device F - Spare *)
                            _128 : REAL; (*Device F - Spare *)
                            _129 : REAL; (*Device F - Spare *)
                            _130 : REAL; (*Device F - Spare *)
                            _131 : REAL; (*Device F - Spare *)
                            _132 : REAL; (*Device F - Spare *)
                            _133 : REAL; (*Device F - Spare *)
                            _134 : REAL; (*Device F - Spare *)
                            _135 : REAL; (*Device F - Spare *)
                            _136 : REAL; (*Device F - Spare *)
                            _137 : REAL; (*Device F - Spare *)
                            _138 : REAL; (*Device F - Spare *)
                            _139 : REAL; (*Device F - Spare *)
                            _140 : REAL; (*Device F - Spare *)
                            _141 : REAL; (*Device F - Spare *)
                            _142 : REAL; (*Device F - Spare *)
                            _143 : REAL; (*Device F - Spare *)
                            _144 : REAL; (*Device F - Spare *)
                            _145 : REAL; (*Device F - Spare *)
                            _146 : REAL; (*Device F - Spare *)
                            _147 : REAL; (*Device F - Spare *)
                            _148 : REAL; (*Device F - Spare *)
                            _149 : REAL; (*Device F - Spare *)
                            _150 : REAL; (*Device F - Spare *)
                            _151 : REAL; (*Device F - Spare *)
                            _152 : REAL; (*Device F - Spare *)
                            _153 : REAL; (*Device F - Spare *)
                            _154 : REAL; (*Device F - Spare *)
                            _155 : REAL; (*Device F - Spare *)
                            _156 : REAL; (*Device F - Spare *)
                            _157 : REAL; (*Device F - Spare *)
                            _158 : REAL; (*Device F - Spare *)
                            _159 : REAL; (*Device F - Spare *)
                            _160 : REAL; (*Device F - Spare *)
                            _161 : REAL; (*Device F - Spare *)
                            _162 : REAL; (*Device F - Spare *)
                            _163 : REAL; (*Device F - Spare *)
                            _164 : REAL; (*Device F - Spare *)
                            _165 : REAL; (*Device F - Spare *)
                            _166 : REAL; (*Device F - Spare *)
                            _167 : REAL; (*Device F - Spare *)
                            _168 : REAL; (*Device F - Spare *)
                            _169 : REAL; (*Device F - Spare *)
                            _170 : REAL; (*Device F - Spare *)
                            _171 : REAL; (*Device F - Spare *)
                            _172 : REAL; (*Device F - Spare *)
                            _173 : REAL; (*Device F - Spare *)
                            _174 : REAL; (*Device F - Spare *)
                            _175 : REAL; (*Device F - Spare *)
                            _176 : REAL; (*Device F - Spare *)
                            _177 : REAL; (*Device F - Spare *)
                            _178 : REAL; (*Device F - Spare *)
                            _179 : REAL; (*Device F - Spare *)
                            _180 : REAL; (*Device F - Spare *)
                            _181 : REAL; (*Device F - Spare *)
                            _182 : REAL; (*Device F - Spare *)
                            _183 : REAL; (*Device F - Spare *)
                            _184 : REAL; (*Device F - Spare *)
                            _185 : REAL; (*Device F - Spare *)
                            _186 : REAL; (*Device F - Spare *)
                            _187 : REAL; (*Device F - Spare *)
                            _188 : REAL; (*Device F - Spare *)
                            _189 : REAL; (*Device F - Spare *)
                            _190 : REAL; (*Device F - Spare *)
                            _191 : REAL; (*Device F - Spare *)
                            _192 : REAL; (*Device F - Spare *)
                            _193 : REAL; (*Device F - Spare *)
                            _194 : REAL; (*Device F - Spare *)
                            _195 : REAL; (*Device F - Spare *)
                            _196 : REAL; (*Device F - Spare *)
                            _197 : REAL; (*Device F - Spare *)
                            _198 : REAL; (*Device F - Spare *)
                            _199 : REAL; (*Device F - Spare *)
                            _200 : REAL; (*Device G - Spare *)
                            _201 : REAL; (*Device G - Spare *)
                            _202 : REAL; (*Device G - Spare *)
                            _203 : REAL; (*Device G - Spare *)
                            _204 : REAL; (*Device G - Spare *)
                            _205 : REAL; (*Device G - Spare *)
                            _206 : REAL; (*Device G - Spare *)
                            _207 : REAL; (*Device G - Spare *)
                            _208 : REAL; (*Device G - Spare *)
                            _209 : REAL; (*Device G - Spare *)
                            _210 : REAL; (*Device G - Spare *)
                            _211 : REAL; (*Device G - Spare *)
                            _212 : REAL; (*Device G - Spare *)
                            _213 : REAL; (*Device G - Spare *)
                            _214 : REAL; (*Device G - Spare *)
                            _215 : REAL; (*Device G - Spare *)
                            _216 : REAL; (*Device G - Spare *)
                            _217 : REAL; (*Device G - Spare *)
                            _218 : REAL; (*Device G - Spare *)
                            _219 : REAL; (*Device G - Spare *)
                            _220 : REAL; (*Device G - Spare *)
                            _221 : REAL; (*Device G - Spare *)
                            _222 : REAL; (*Device G - Spare *)
                            _223 : REAL; (*Device G - Spare *)
                            _224 : REAL; (*Device G - Spare *)
                            _225 : REAL; (*Device G - Spare *)
                            _226 : REAL; (*Device G - Spare *)
                            _227 : REAL; (*Device G - Spare *)
                            _228 : REAL; (*Device G - Spare *)
                            _229 : REAL; (*Device G - Spare *)
                            _230 : REAL; (*Device G - Spare *)
                            _231 : REAL; (*Device G - Spare *)
                            _232 : REAL; (*Device G - Spare *)
                            _233 : REAL; (*Device G - Spare *)
                            _234 : REAL; (*Device G - Spare *)
                            _235 : REAL; (*Device G - Spare *)
                            _236 : REAL; (*Device G - Spare *)
                            _237 : REAL; (*Device G - Spare *)
                            _238 : REAL; (*Device G - Spare *)
                            _239 : REAL; (*Device G - Spare *)
                            _240 : REAL; (*Device G - Spare *)
                            _241 : REAL; (*Device G - Spare *)
                            _242 : REAL; (*Device G - Spare *)
                            _243 : REAL; (*Device G - Spare *)
                            _244 : REAL; (*Device G - Spare *)
                            _245 : REAL; (*Device G - Spare *)
                            _246 : REAL; (*Device G - Spare *)
                            _247 : REAL; (*Device G - Spare *)
                            _248 : REAL; (*Device G - Spare *)
                            _249 : REAL; (*Device G - Spare *)
                            _250 : REAL; (*Device G - Spare *)
                            _251 : REAL; (*Device G - Spare *)
                            _252 : REAL; (*Device G - Spare *)
                            _253 : REAL; (*Device G - Spare *)
                            _254 : REAL; (*Device G - Spare *)
                            _255 : REAL; (*Device G - Spare *)
                            _256 : REAL; (*Device G - Spare *)
                            _257 : REAL; (*Device G - Spare *)
                            _258 : REAL; (*Device G - Spare *)
                            _259 : REAL; (*Device G - Spare *)
                            _260 : REAL; (*Device G - Spare *)
                            _261 : REAL; (*Device G - Spare *)
                            _262 : REAL; (*Device G - Spare *)
                            _263 : REAL; (*Device G - Spare *)
                            _264 : REAL; (*Device G - Spare *)
                            _265 : REAL; (*Device G - Spare *)
                            _266 : REAL; (*Device G - Spare *)
                            _267 : REAL; (*Device G - Spare *)
                            _268 : REAL; (*Device G - Spare *)
                            _269 : REAL; (*Device G - Spare *)
                            _270 : REAL; (*Device G - Spare *)
                            _271 : REAL; (*Device G - Spare *)
                            _272 : REAL; (*Device G - Spare *)
                            _273 : REAL; (*Device G - Spare *)
                            _274 : REAL; (*Device G - Spare *)
                            _275 : REAL; (*Device G - Spare *)
                            _276 : REAL; (*Device G - Spare *)
                            _277 : REAL; (*Device G - Spare *)
                            _278 : REAL; (*Device G - Spare *)
                            _279 : REAL; (*Device G - Spare *)
                            _280 : REAL; (*Device G - Spare *)
                            _281 : REAL; (*Device G - Spare *)
                            _282 : REAL; (*Device G - Spare *)
                            _283 : REAL; (*Device G - Spare *)
                            _284 : REAL; (*Device G - Spare *)
                            _285 : REAL; (*Device G - Spare *)
                            _286 : REAL; (*Device G - Spare *)
                            _287 : REAL; (*Device G - Spare *)
                            _288 : REAL; (*Device G - Spare *)
                            _289 : REAL; (*Device G - Spare *)
                            _290 : REAL; (*Device G - Spare *)
                            _291 : REAL; (*Device G - Spare *)
                            _292 : REAL; (*Device G - Spare *)
                            _293 : REAL; (*Device G - Spare *)
                            _294 : REAL; (*Device G - Spare *)
                            _295 : REAL; (*Device G - Spare *)
                            _296 : REAL; (*Device G - Spare *)
                            _297 : REAL; (*Device G - Spare *)
                            _298 : REAL; (*Device G - Spare *)
                            _299 : REAL; (*Device G - Spare *)
                            _300 : REAL; (*Device S - Spare *)
                            _301 : REAL; (*Device S - Spare *)
                            _302 : REAL; (*Device S - Spare *)
                            _303 : REAL; (*Device S - Spare *)
                            _304 : REAL; (*Device S - Spare *)
                            _305 : REAL; (*Device S - Spare *)
                            _306 : REAL; (*Device S - Spare *)
                            _307 : REAL; (*Device S - Spare *)
                            _308 : REAL; (*Device S - Spare *)
                            _309 : REAL; (*Device S - Spare *)
                            _310 : REAL; (*Device S - Spare *)
                            _311 : REAL; (*Device S - Spare *)
                            _312 : REAL; (*Device S - Spare *)
                            _313 : REAL; (*Device S - Spare *)
                            _314 : REAL; (*Device S - Spare *)
                            _315 : REAL; (*Device S - Spare *)
                            _316 : REAL; (*Device S - Spare *)
                            _317 : REAL; (*Device S - Spare *)
                            _318 : REAL; (*Device S - Spare *)
                            _319 : REAL; (*Device S - Spare *)
                            _320 : REAL; (*Device S - Spare *)
                            _321 : REAL; (*Device S - Spare *)
                            _322 : REAL; (*Device S - Spare *)
                            _323 : REAL; (*Device S - Spare *)
                            _324 : REAL; (*Device S - Spare *)
                            _325 : REAL; (*Device S - Spare *)
                            _326 : REAL; (*Device S - Spare *)
                            _327 : REAL; (*Device S - Spare *)
                            _328 : REAL; (*Device S - Spare *)
                            _329 : REAL; (*Device S - Spare *)
                            _330 : REAL; (*Device S - Spare *)
                            _331 : REAL; (*Device S - Spare *)
                            _332 : REAL; (*Device S - Spare *)
                            _333 : REAL; (*Device S - Spare *)
                            _334 : REAL; (*Device S - Spare *)
                            _335 : REAL; (*Device S - Spare *)
                            _336 : REAL; (*Device S - Spare *)
                            _337 : REAL; (*Device S - Spare *)
                            _338 : REAL; (*Device S - Spare *)
                            _339 : REAL; (*Device S - Spare *)
                            _340 : REAL; (*Device S - Spare *)
                            _341 : REAL; (*Device S - Spare *)
                            _342 : REAL; (*Device S - Spare *)
                            _343 : REAL; (*Device S - Spare *)
                            _344 : REAL; (*Device S - Spare *)
                            _345 : REAL; (*Device S - Spare *)
                            _346 : REAL; (*Device S - Spare *)
                            _347 : REAL; (*Device S - Spare *)
                            _348 : REAL; (*Device S - Spare *)
                            _349 : REAL; (*Device S - Spare *)
                            _350 : REAL; (*Device S - Spare *)
                            _351 : REAL; (*Device S - Spare *)
                            _352 : REAL; (*Device S - Spare *)
                            _353 : REAL; (*Device S - Spare *)
                            _354 : REAL; (*Device S - Spare *)
                            _355 : REAL; (*Device S - Spare *)
                            _356 : REAL; (*Device S - Spare *)
                            _357 : REAL; (*Device S - Spare *)
                            _358 : REAL; (*Device S - Spare *)
                            _359 : REAL; (*Device S - Spare *)
                            _360 : REAL; (*Device S - Spare *)
                            _361 : REAL; (*Device S - Spare *)
                            _362 : REAL; (*Device S - Spare *)
                            _363 : REAL; (*Device S - Spare *)
                            _364 : REAL; (*Device S - Spare *)
                            _365 : REAL; (*Device S - Spare *)
                            _366 : REAL; (*Device S - Spare *)
                            _367 : REAL; (*Device S - Spare *)
                            _368 : REAL; (*Device S - Spare *)
                            _369 : REAL; (*Device S - Spare *)
                            _370 : REAL; (*Device S - Spare *)
                            _371 : REAL; (*Device S - Spare *)
                            _372 : REAL; (*Device S - Spare *)
                            _373 : REAL; (*Device S - Spare *)
                            _374 : REAL; (*Device S - Spare *)
                            _375 : REAL; (*Device S - Spare *)
                            _376 : REAL; (*Device S - Spare *)
                            _377 : REAL; (*Device S - Spare *)
                            _378 : REAL; (*Device S - Spare *)
                            _379 : REAL; (*Device S - Spare *)
                            _380 : REAL; (*Device S - Spare *)
                            _381 : REAL; (*Device S - Spare *)
                            _382 : REAL; (*Device S - Spare *)
                            _383 : REAL; (*Device S - Spare *)
                            _384 : REAL; (*Device S - Spare *)
                            _385 : REAL; (*Device S - Spare *)
                            _386 : REAL; (*Device S - Spare *)
                            _387 : REAL; (*Device S - Spare *)
                            _388 : REAL; (*Device S - Spare *)
                            _389 : REAL; (*Device S - Spare *)
                            _390 : REAL; (*Device S - Spare *)
                            _391 : REAL; (*Device S - Spare *)
                            _392 : REAL; (*Device S - Spare *)
                            _393 : REAL; (*Device S - Spare *)
                            _394 : REAL; (*Device S - Spare *)
                            _395 : REAL; (*Device S - Spare *)
                            _396 : REAL; (*Device S - Spare *)
                            _397 : REAL; (*Device S - Spare *)
                            _398 : REAL; (*Device S - Spare *)
                            _399 : REAL; (*Device S - Spare *)
                            _400 : REAL; (*SPARE - Spare *)
                            _401 : REAL; (*SPARE - Spare *)
                            _402 : REAL; (*SPARE - Spare *)
                            _403 : REAL; (*SPARE - Spare *)
                            _404 : REAL; (*SPARE - Spare *)
                            _405 : REAL; (*SPARE - Spare *)
                            _406 : REAL; (*SPARE - Spare *)
                            _407 : REAL; (*SPARE - Spare *)
                            _408 : REAL; (*SPARE - Spare *)
                            _409 : REAL; (*SPARE - Spare *)
                            _410 : REAL; (*SPARE - Spare *)
                            _411 : REAL; (*SPARE - Spare *)
                            _412 : REAL; (*SPARE - Spare *)
                            _413 : REAL; (*SPARE - Spare *)
                            _414 : REAL; (*SPARE - Spare *)
                            _415 : REAL; (*SPARE - Spare *)
                            _416 : REAL; (*SPARE - Spare *)
                            _417 : REAL; (*SPARE - Spare *)
                            _418 : REAL; (*SPARE - Spare *)
                            _419 : REAL; (*SPARE - Spare *)
                            _420 : REAL; (*SPARE - Spare *)
                            _421 : REAL; (*SPARE - Spare *)
                            _422 : REAL; (*SPARE - Spare *)
                            _423 : REAL; (*SPARE - Spare *)
                            _424 : REAL; (*SPARE - Spare *)
                            _425 : REAL; (*SPARE - Spare *)
                            _426 : REAL; (*SPARE - Spare *)
                            _427 : REAL; (*SPARE - Spare *)
                            _428 : REAL; (*SPARE - Spare *)
                            _429 : REAL; (*SPARE - Spare *)
                            _430 : REAL; (*SPARE - Spare *)
                            _431 : REAL; (*SPARE - Spare *)
                            _432 : REAL; (*SPARE - Spare *)
                            _433 : REAL; (*SPARE - Spare *)
                            _434 : REAL; (*SPARE - Spare *)
                            _435 : REAL; (*SPARE - Spare *)
                            _436 : REAL; (*SPARE - Spare *)
                            _437 : REAL; (*SPARE - Spare *)
                            _438 : REAL; (*SPARE - Spare *)
                            _439 : REAL; (*SPARE - Spare *)
                            _440 : REAL; (*SPARE - Spare *)
                            _441 : REAL; (*SPARE - Spare *)
                            _442 : REAL; (*SPARE - Spare *)
                            _443 : REAL; (*SPARE - Spare *)
                            _444 : REAL; (*SPARE - Spare *)
                            _445 : REAL; (*SPARE - Spare *)
                            _446 : REAL; (*SPARE - Spare *)
                            _447 : REAL; (*SPARE - Spare *)
                            _448 : REAL; (*SPARE - Spare *)
                            _449 : REAL; (*SPARE - Spare *)
                            _450 : REAL; (*SPARE - Spare *)
                            _451 : REAL; (*SPARE - Spare *)
                            _452 : REAL; (*SPARE - Spare *)
                            _453 : REAL; (*SPARE - Spare *)
                            _454 : REAL; (*SPARE - Spare *)
                            _455 : REAL; (*SPARE - Spare *)
                            _456 : REAL; (*SPARE - Spare *)
                            _457 : REAL; (*SPARE - Spare *)
                            _458 : REAL; (*SPARE - Spare *)
                            _459 : REAL; (*SPARE - Spare *)
                            _460 : REAL; (*SPARE - Spare *)
                            _461 : REAL; (*SPARE - Spare *)
                            _462 : REAL; (*SPARE - Spare *)
                            _463 : REAL; (*SPARE - Spare *)
                            _464 : REAL; (*SPARE - Spare *)
                            _465 : REAL; (*SPARE - Spare *)
                            _466 : REAL; (*SPARE - Spare *)
                            _467 : REAL; (*SPARE - Spare *)
                            _468 : REAL; (*SPARE - Spare *)
                            _469 : REAL; (*SPARE - Spare *)
                            _470 : REAL; (*SPARE - Spare *)
                            _471 : REAL; (*SPARE - Spare *)
                            _472 : REAL; (*SPARE - Spare *)
                            _473 : REAL; (*SPARE - Spare *)
                            _474 : REAL; (*SPARE - Spare *)
                            _475 : REAL; (*SPARE - Spare *)
                            _476 : REAL; (*SPARE - Spare *)
                            _477 : REAL; (*SPARE - Spare *)
                            _478 : REAL; (*SPARE - Spare *)
                            _479 : REAL; (*SPARE - Spare *)
                            _480 : REAL; (*SPARE - Spare *)
                            _481 : REAL; (*SPARE - Spare *)
                            _482 : REAL; (*SPARE - Spare *)
                            _483 : REAL; (*SPARE - Spare *)
                            _484 : REAL; (*SPARE - Spare *)
                            _485 : REAL; (*SPARE - Spare *)
                            _486 : REAL; (*SPARE - Spare *)
                            _487 : REAL; (*SPARE - Spare *)
                            _488 : REAL; (*SPARE - Spare *)
                            _489 : REAL; (*SPARE - Spare *)
                            _490 : REAL; (*SPARE - Spare *)
                            _491 : REAL; (*SPARE - Spare *)
                            _492 : REAL; (*SPARE - Spare *)
                            _493 : REAL; (*SPARE - Spare *)
                            _494 : REAL; (*SPARE - Spare *)
                            _495 : REAL; (*SPARE - Spare *)
                            _496 : REAL; (*SPARE - Spare *)
                            _497 : REAL; (*SPARE - Spare *)
                            _498 : REAL; (*SPARE - Spare *)
                            _499 : REAL; (*SPARE - Spare *)
                            _500 : REAL; (*Device X - PPX201 - OUT Min [Hz]*)
                            _501 : REAL; (*Device X - PPX201 - OUT Max [Hz]*)
                            _502 : REAL; (*Device X - PPX201 - Spare *)
                            _503 : REAL; (*Device X - PPX201 - Spare *)
                            _504 : REAL; (*Device X - PPX201 - Spare *)
                            _505 : REAL; (*Device X - PPX202 - OUT Min [Hz]*)
                            _506 : REAL; (*Device X - PPX202 - OUT Max [Hz]*)
                            _507 : REAL; (*Device X - PPX202 - Spare *)
                            _508 : REAL; (*Device X - PPX202 - Spare *)
                            _509 : REAL; (*Device X - PPX202 - Spare *)
                            _510 : REAL; (*Device X - PPX203 - OUT Min [Hz]*)
                            _511 : REAL; (*Device X - PPX203 - OUT Max [Hz]*)
                            _512 : REAL; (*Device X - PPX203 - Spare *)
                            _513 : REAL; (*Device X - PPX203 - Spare *)
                            _514 : REAL; (*Device X - PPX203 - Spare *)
                            _515 : REAL; (*Device X - PPX204 - OUT Min [Hz]*)
                            _516 : REAL; (*Device X - PPX204 - OUT Max [Hz]*)
                            _517 : REAL; (*Device X - PPX204 - Spare *)
                            _518 : REAL; (*Device X - PPX204 - Spare *)
                            _519 : REAL; (*Device X - PPX204 - Spare *)
                            _520 : REAL; (*Device X - PPX205 - OUT Min [Hz]*)
                            _521 : REAL; (*Device X - PPX205 - OUT Max [Hz]*)
                            _522 : REAL; (*Device X - PPX205 - Spare *)
                            _523 : REAL; (*Device X - PPX205 - Spare *)
                            _524 : REAL; (*Device X - PPX205 - Spare *)
                            _525 : REAL; (*Device X - PPX206 - OUT Min [Hz]*)
                            _526 : REAL; (*Device X - PPX206 - OUT Max [Hz]*)
                            _527 : REAL; (*Device X - PPX206 - Spare *)
                            _528 : REAL; (*Device X - PPX206 - Spare *)
                            _529 : REAL; (*Device X - PPX206 - Spare *)
                            _530 : REAL; (*Device X - PPX207 - OUT Min [Hz]*)
                            _531 : REAL; (*Device X - PPX207 - OUT Max [Hz]*)
                            _532 : REAL; (*Device X - PPX207 - Spare *)
                            _533 : REAL; (*Device X - PPX207 - Spare *)
                            _534 : REAL; (*Device X - PPX207 - Spare *)
                            _535 : REAL; (*Device X - PPX208 - OUT Min [Hz]*)
                            _536 : REAL; (*Device X - PPX208 - OUT Max [Hz]*)
                            _537 : REAL; (*Device X - PPX208 - Spare *)
                            _538 : REAL; (*Device X - PPX208 - Spare *)
                            _539 : REAL; (*Device X - PPX208 - Spare *)
                            _540 : REAL; (*Device X - PPX209 - OUT Min [Hz]*)
                            _541 : REAL; (*Device X - PPX209 - OUT Max [Hz]*)
                            _542 : REAL; (*Device X - PPX209 - Spare *)
                            _543 : REAL; (*Device X - PPX209 - Spare *)
                            _544 : REAL; (*Device X - PPX209 - Spare *)
                            _545 : REAL; (*Device X - PPX210 - OUT Min [Hz]*)
                            _546 : REAL; (*Device X - PPX210 - OUT Max [Hz]*)
                            _547 : REAL; (*Device X - PPX210 - Spare *)
                            _548 : REAL; (*Device X - PPX210 - Spare *)
                            _549 : REAL; (*Device X - PPX210 - Spare *)
                            _550 : REAL; (*Device X - Spare *)
                            _551 : REAL; (*Device X - Spare *)
                            _552 : REAL; (*Device X - Spare *)
                            _553 : REAL; (*Device X - Spare *)
                            _554 : REAL; (*Device X - Spare *)
                            _555 : REAL; (*Device X - Spare *)
                            _556 : REAL; (*Device X - Spare *)
                            _557 : REAL; (*Device X - Spare *)
                            _558 : REAL; (*Device X - Spare *)
                            _559 : REAL; (*Device X - Spare *)
                            _560 : REAL; (*Device X - Spare *)
                            _561 : REAL; (*Device X - Spare *)
                            _562 : REAL; (*Device X - Spare *)
                            _563 : REAL; (*Device X - Spare *)
                            _564 : REAL; (*Device X - Spare *)
                            _565 : REAL; (*Device X - Spare *)
                            _566 : REAL; (*Device X - Spare *)
                            _567 : REAL; (*Device X - Spare *)
                            _568 : REAL; (*Device X - Spare *)
                            _569 : REAL; (*Device X - Spare *)
                            _570 : REAL; (*Device X - Spare *)
                            _571 : REAL; (*Device X - Spare *)
                            _572 : REAL; (*Device X - Spare *)
                            _573 : REAL; (*Device X - Spare *)
                            _574 : REAL; (*Device X - Spare *)
                            _575 : REAL; (*Device X - Spare *)
                            _576 : REAL; (*Device X - Spare *)
                            _577 : REAL; (*Device X - Spare *)
                            _578 : REAL; (*Device X - Spare *)
                            _579 : REAL; (*Device X - Spare *)
                            _580 : REAL; (*Device X - Spare *)
                            _581 : REAL; (*Device X - Spare *)
                            _582 : REAL; (*Device X - Spare *)
                            _583 : REAL; (*Device X - Spare *)
                            _584 : REAL; (*Device X - Spare *)
                            _585 : REAL; (*Device X - Spare *)
                            _586 : REAL; (*Device X - Spare *)
                            _587 : REAL; (*Device X - Spare *)
                            _588 : REAL; (*Device X - Spare *)
                            _589 : REAL; (*Device X - Spare *)
                            _590 : REAL; (*Device X - Spare *)
                            _591 : REAL; (*Device X - Spare *)
                            _592 : REAL; (*Device X - Spare *)
                            _593 : REAL; (*Device X - Spare *)
                            _594 : REAL; (*Device X - Spare *)
                            _595 : REAL; (*Device X - Spare *)
                            _596 : REAL; (*Device X - Spare *)
                            _597 : REAL; (*Device X - Spare *)
                            _598 : REAL; (*Device X - Spare *)
                            _599 : REAL; (*Device X - Spare *)
                            _600 : REAL; (*Device J - Spare *)
                            _601 : REAL; (*Device J - Spare *)
                            _602 : REAL; (*Device J - Spare *)
                            _603 : REAL; (*Device J - Spare *)
                            _604 : REAL; (*Device J - Spare *)
                            _605 : REAL; (*Device J - Spare *)
                            _606 : REAL; (*Device J - Spare *)
                            _607 : REAL; (*Device J - Spare *)
                            _608 : REAL; (*Device J - Spare *)
                            _609 : REAL; (*Device J - Spare *)
                            _610 : REAL; (*Device J - Spare *)
                            _611 : REAL; (*Device J - Spare *)
                            _612 : REAL; (*Device J - Spare *)
                            _613 : REAL; (*SPARE - Spare *)
                            _614 : REAL; (*SPARE - Spare *)
                            _615 : REAL; (*SPARE - Spare *)
                            _616 : REAL; (*SPARE - Spare *)
                            _617 : REAL; (*SPARE - Spare *)
                            _618 : REAL; (*SPARE - Spare *)
                            _619 : REAL; (*SPARE - Spare *)
                            _620 : REAL; (*SPARE - Spare *)
                            _621 : REAL; (*SPARE - Spare *)
                            _622 : REAL; (*SPARE - Spare *)
                            _623 : REAL; (*SPARE - Spare *)
                            _624 : REAL; (*SPARE - Spare *)
                            _625 : REAL; (*SPARE - Spare *)
                            _626 : REAL; (*SPARE - Spare *)
                            _627 : REAL; (*SPARE - Spare *)
                            _628 : REAL; (*SPARE - Spare *)
                            _629 : REAL; (*SPARE - Spare *)
                            _630 : REAL; (*SPARE - Spare *)
                            _631 : REAL; (*SPARE - Spare *)
                            _632 : REAL; (*SPARE - Spare *)
                            _633 : REAL; (*SPARE - Spare *)
                            _634 : REAL; (*SPARE - Spare *)
                            _635 : REAL; (*SPARE - Spare *)
                            _636 : REAL; (*SPARE - Spare *)
                            _637 : REAL; (*SPARE - Spare *)
                            _638 : REAL; (*SPARE - Spare *)
                            _639 : REAL; (*SPARE - Spare *)
                            _640 : REAL; (*SPARE - Spare *)
                            _641 : REAL; (*SPARE - Spare *)
                            _642 : REAL; (*SPARE - Spare *)
                            _643 : REAL; (*SPARE - Spare *)
                            _644 : REAL; (*SPARE - Spare *)
                            _645 : REAL; (*SPARE - Spare *)
                            _646 : REAL; (*SPARE - Spare *)
                            _647 : REAL; (*SPARE - Spare *)
                            _648 : REAL; (*SPARE - Spare *)
                            _649 : REAL; (*SPARE - Spare *)
                            _650 : REAL; (*SPARE - Spare *)
                            _651 : REAL; (*SPARE - Spare *)
                            _652 : REAL; (*SPARE - Spare *)
                            _653 : REAL; (*SPARE - Spare *)
                            _654 : REAL; (*SPARE - Spare *)
                            _655 : REAL; (*SPARE - Spare *)
                            _656 : REAL; (*SPARE - Spare *)
                            _657 : REAL; (*SPARE - Spare *)
                            _658 : REAL; (*SPARE - Spare *)
                            _659 : REAL; (*SPARE - Spare *)
                            _660 : REAL; (*SPARE - Spare *)
                            _661 : REAL; (*SPARE - Spare *)
                            _662 : REAL; (*SPARE - Spare *)
                            _663 : REAL; (*SPARE - Spare *)
                            _664 : REAL; (*SPARE - Spare *)
                            _665 : REAL; (*SPARE - Spare *)
                            _666 : REAL; (*SPARE - Spare *)
                            _667 : REAL; (*SPARE - Spare *)
                            _668 : REAL; (*SPARE - Spare *)
                            _669 : REAL; (*SPARE - Spare *)
                            _670 : REAL; (*SPARE - Spare *)
                            _671 : REAL; (*SPARE - Spare *)
                            _672 : REAL; (*SPARE - Spare *)
                            _673 : REAL; (*SPARE - Spare *)
                            _674 : REAL; (*SPARE - Spare *)
                            _675 : REAL; (*SPARE - Spare *)
                            _676 : REAL; (*SPARE - Spare *)
                            _677 : REAL; (*SPARE - Spare *)
                            _678 : REAL; (*SPARE - Spare *)
                            _679 : REAL; (*SPARE - Spare *)
                            _680 : REAL; (*SPARE - Spare *)
                            _681 : REAL; (*SPARE - Spare *)
                            _682 : REAL; (*SPARE - Spare *)
                            _683 : REAL; (*SPARE - Spare *)
                            _684 : REAL; (*SPARE - Spare *)
                            _685 : REAL; (*SPARE - Spare *)
                            _686 : REAL; (*SPARE - Spare *)
                            _687 : REAL; (*SPARE - Spare *)
                            _688 : REAL; (*SPARE - Spare *)
                            _689 : REAL; (*SPARE - Spare *)
                            _690 : REAL; (*SPARE - Spare *)
                            _691 : REAL; (*SPARE - Spare *)
                            _692 : REAL; (*SPARE - Spare *)
                            _693 : REAL; (*SPARE - Spare *)
                            _694 : REAL; (*SPARE - Spare *)
                            _695 : REAL; (*SPARE - Spare *)
                            _696 : REAL; (*SPARE - Spare *)
                            _697 : REAL; (*SPARE - Spare *)
                            _698 : REAL; (*SPARE - Spare *)
                            _699 : REAL; (*SPARE - Spare *)
                            _700 : REAL; (*SPARE - Spare *)
                            _701 : REAL; (*SPARE - Spare *)
                            _702 : REAL; (*SPARE - Spare *)
                            _703 : REAL; (*SPARE - Spare *)
                            _704 : REAL; (*SPARE - Spare *)
                            _705 : REAL; (*SPARE - Spare *)
                            _706 : REAL; (*SPARE - Spare *)
                            _707 : REAL; (*SPARE - Spare *)
                            _708 : REAL; (*SPARE - Spare *)
                            _709 : REAL; (*SPARE - Spare *)
                            _710 : REAL; (*SPARE - Spare *)
                            _711 : REAL; (*SPARE - Spare *)
                            _712 : REAL; (*SPARE - Spare *)
                            _713 : REAL; (*SPARE - Spare *)
                            _714 : REAL; (*SPARE - Spare *)
                            _715 : REAL; (*SPARE - Spare *)
                            _716 : REAL; (*SPARE - Spare *)
                            _717 : REAL; (*SPARE - Spare *)
                            _718 : REAL; (*SPARE - Spare *)
                            _719 : REAL; (*SPARE - Spare *)
                            _720 : REAL; (*SPARE - Spare *)
                            _721 : REAL; (*SPARE - Spare *)
                            _722 : REAL; (*SPARE - Spare *)
                            _723 : REAL; (*SPARE - Spare *)
                            _724 : REAL; (*SPARE - Spare *)
                            _725 : REAL; (*SPARE - Spare *)
                            _726 : REAL; (*SPARE - Spare *)
                            _727 : REAL; (*SPARE - Spare *)
                            _728 : REAL; (*SPARE - Spare *)
                            _729 : REAL; (*SPARE - Spare *)
                            _730 : REAL; (*SPARE - Spare *)
                            _731 : REAL; (*SPARE - Spare *)
                            _732 : REAL; (*SPARE - Spare *)
                            _733 : REAL; (*SPARE - Spare *)
                            _734 : REAL; (*SPARE - Spare *)
                            _735 : REAL; (*SPARE - Spare *)
                            _736 : REAL; (*SPARE - Spare *)
                            _737 : REAL; (*SPARE - Spare *)
                            _738 : REAL; (*SPARE - Spare *)
                            _739 : REAL; (*SPARE - Spare *)
                            _740 : REAL; (*SPARE - Spare *)
                            _741 : REAL; (*SPARE - Spare *)
                            _742 : REAL; (*SPARE - Spare *)
                            _743 : REAL; (*SPARE - Spare *)
                            _744 : REAL; (*SPARE - Spare *)
                            _745 : REAL; (*SPARE - Spare *)
                            _746 : REAL; (*SPARE - Spare *)
                            _747 : REAL; (*SPARE - Spare *)
                            _748 : REAL; (*SPARE - Spare *)
                            _749 : REAL; (*SPARE - Spare *)
                            _750 : REAL; (*SPARE - Spare *)
                            _751 : REAL; (*SPARE - Spare *)
                            _752 : REAL; (*SPARE - Spare *)
                            _753 : REAL; (*SPARE - Spare *)
                            _754 : REAL; (*SPARE - Spare *)
                            _755 : REAL; (*SPARE - Spare *)
                            _756 : REAL; (*SPARE - Spare *)
                            _757 : REAL; (*SPARE - Spare *)
                            _758 : REAL; (*SPARE - Spare *)
                            _759 : REAL; (*SPARE - Spare *)
                            _760 : REAL; (*SPARE - Spare *)
                            _761 : REAL; (*SPARE - Spare *)
                            _762 : REAL; (*SPARE - Spare *)
                            _763 : REAL; (*SPARE - Spare *)
                            _764 : REAL; (*SPARE - Spare *)
                            _765 : REAL; (*SPARE - Spare *)
                            _766 : REAL; (*SPARE - Spare *)
                            _767 : REAL; (*SPARE - Spare *)
                            _768 : REAL; (*SPARE - Spare *)
                            _769 : REAL; (*SPARE - Spare *)
                            _770 : REAL; (*SPARE - Spare *)
                            _771 : REAL; (*SPARE - Spare *)
                            _772 : REAL; (*SPARE - Spare *)
                            _773 : REAL; (*SPARE - Spare *)
                            _774 : REAL; (*SPARE - Spare *)
                            _775 : REAL; (*SPARE - Spare *)
                            _776 : REAL; (*SPARE - Spare *)
                            _777 : REAL; (*SPARE - Spare *)
                            _778 : REAL; (*SPARE - Spare *)
                            _779 : REAL; (*SPARE - Spare *)
                            _780 : REAL; (*SPARE - Spare *)
                            _781 : REAL; (*SPARE - Spare *)
                            _782 : REAL; (*SPARE - Spare *)
                            _783 : REAL; (*SPARE - Spare *)
                            _784 : REAL; (*SPARE - Spare *)
                            _785 : REAL; (*SPARE - Spare *)
                            _786 : REAL; (*SPARE - Spare *)
                            _787 : REAL; (*SPARE - Spare *)
                            _788 : REAL; (*SPARE - Spare *)
                            _789 : REAL; (*SPARE - Spare *)
                            _790 : REAL; (*SPARE - Spare *)
                            _791 : REAL; (*SPARE - Spare *)
                            _792 : REAL; (*SPARE - Spare *)
                            _793 : REAL; (*SPARE - Spare *)
                            _794 : REAL; (*SPARE - Spare *)
                            _795 : REAL; (*SPARE - Spare *)
                            _796 : REAL; (*SPARE - Spare *)
                            _797 : REAL; (*SPARE - Spare *)
                            _798 : REAL; (*SPARE - Spare *)
                            _799 : REAL; (*SPARE - Spare *)
                            _800 : REAL; (*SPARE - Spare *)
                            _801 : REAL; (*SPARE - Spare *)
                            _802 : REAL; (*SPARE - Spare *)
                            _803 : REAL; (*SPARE - Spare *)
                            _804 : REAL; (*SPARE - Spare *)
                            _805 : REAL; (*SPARE - Spare *)
                            _806 : REAL; (*SPARE - Spare *)
                            _807 : REAL; (*SPARE - Spare *)
                            _808 : REAL; (*SPARE - Spare *)
                            _809 : REAL; (*SPARE - Spare *)
                            _810 : REAL; (*SPARE - Spare *)
                            _811 : REAL; (*SPARE - Spare *)
                            _812 : REAL; (*SPARE - Spare *)
                            _813 : REAL; (*SPARE - Spare *)
                            _814 : REAL; (*SPARE - Spare *)
                            _815 : REAL; (*SPARE - Spare *)
                            _816 : REAL; (*SPARE - Spare *)
                            _817 : REAL; (*SPARE - Spare *)
                            _818 : REAL; (*SPARE - Spare *)
                            _819 : REAL; (*SPARE - Spare *)
                            _820 : REAL; (*SPARE - Spare *)
                            _821 : REAL; (*SPARE - Spare *)
                            _822 : REAL; (*SPARE - Spare *)
                            _823 : REAL; (*SPARE - Spare *)
                            _824 : REAL; (*SPARE - Spare *)
                            _825 : REAL; (*SPARE - Spare *)
                            _826 : REAL; (*SPARE - Spare *)
                            _827 : REAL; (*SPARE - Spare *)
                            _828 : REAL; (*SPARE - Spare *)
                            _829 : REAL; (*SPARE - Spare *)
                            _830 : REAL; (*SPARE - Spare *)
                            _831 : REAL; (*SPARE - Spare *)
                            _832 : REAL; (*SPARE - Spare *)
                            _833 : REAL; (*SPARE - Spare *)
                            _834 : REAL; (*SPARE - Spare *)
                            _835 : REAL; (*SPARE - Spare *)
                            _836 : REAL; (*SPARE - Spare *)
                            _837 : REAL; (*SPARE - Spare *)
                            _838 : REAL; (*SPARE - Spare *)
                            _839 : REAL; (*SPARE - Spare *)
                            _840 : REAL; (*SPARE - Spare *)
                            _841 : REAL; (*SPARE - Spare *)
                            _842 : REAL; (*SPARE - Spare *)
                            _843 : REAL; (*SPARE - Spare *)
                            _844 : REAL; (*SPARE - Spare *)
                            _845 : REAL; (*SPARE - Spare *)
                            _846 : REAL; (*SPARE - Spare *)
                            _847 : REAL; (*SPARE - Spare *)
                            _848 : REAL; (*SPARE - Spare *)
                            _849 : REAL; (*SPARE - Spare *)
                            _850 : REAL; (*SPARE - Spare *)
                            _851 : REAL; (*SPARE - Spare *)
                            _852 : REAL; (*SPARE - Spare *)
                            _853 : REAL; (*SPARE - Spare *)
                            _854 : REAL; (*SPARE - Spare *)
                            _855 : REAL; (*SPARE - Spare *)
                            _856 : REAL; (*SPARE - Spare *)
                            _857 : REAL; (*SPARE - Spare *)
                            _858 : REAL; (*SPARE - Spare *)
                            _859 : REAL; (*SPARE - Spare *)
                            _860 : REAL; (*SPARE - Spare *)
                            _861 : REAL; (*SPARE - Spare *)
                            _862 : REAL; (*SPARE - Spare *)
                            _863 : REAL; (*SPARE - Spare *)
                            _864 : REAL; (*SPARE - Spare *)
                            _865 : REAL; (*SPARE - Spare *)
                            _866 : REAL; (*SPARE - Spare *)
                            _867 : REAL; (*SPARE - Spare *)
                            _868 : REAL; (*SPARE - Spare *)
                            _869 : REAL; (*SPARE - Spare *)
                            _870 : REAL; (*SPARE - Spare *)
                            _871 : REAL; (*SPARE - Spare *)
                            _872 : REAL; (*SPARE - Spare *)
                            _873 : REAL; (*SPARE - Spare *)
                            _874 : REAL; (*SPARE - Spare *)
                            _875 : REAL; (*SPARE - Spare *)
                            _876 : REAL; (*SPARE - Spare *)
                            _877 : REAL; (*SPARE - Spare *)
                            _878 : REAL; (*SPARE - Spare *)
                            _879 : REAL; (*SPARE - Spare *)
                            _880 : REAL; (*SPARE - Spare *)
                            _881 : REAL; (*SPARE - Spare *)
                            _882 : REAL; (*SPARE - Spare *)
                            _883 : REAL; (*SPARE - Spare *)
                            _884 : REAL; (*SPARE - Spare *)
                            _885 : REAL; (*SPARE - Spare *)
                            _886 : REAL; (*SPARE - Spare *)
                            _887 : REAL; (*SPARE - Spare *)
                            _888 : REAL; (*SPARE - Spare *)
                            _889 : REAL; (*SPARE - Spare *)
                            _890 : REAL; (*SPARE - Spare *)
                            _891 : REAL; (*SPARE - Spare *)
                            _892 : REAL; (*SPARE - Spare *)
                            _893 : REAL; (*SPARE - Spare *)
                            _894 : REAL; (*SPARE - Spare *)
                            _895 : REAL; (*SPARE - Spare *)
                            _896 : REAL; (*SPARE - Spare *)
                            _897 : REAL; (*SPARE - Spare *)
                            _898 : REAL; (*SPARE - Spare *)
                            _899 : REAL; (*SPARE - Spare *)
                            _900 : REAL; (*SPARE - Spare *)
                            _901 : REAL; (*SPARE - Spare *)
                            _902 : REAL; (*SPARE - Spare *)
                            _903 : REAL; (*SPARE - Spare *)
                            _904 : REAL; (*SPARE - Spare *)
                            _905 : REAL; (*SPARE - Spare *)
                            _906 : REAL; (*SPARE - Spare *)
                            _907 : REAL; (*SPARE - Spare *)
                            _908 : REAL; (*SPARE - Spare *)
                            _909 : REAL; (*SPARE - Spare *)
                            _910 : REAL; (*SPARE - Spare *)
                            _911 : REAL; (*SPARE - Spare *)
                            _912 : REAL; (*SPARE - Spare *)
                            _913 : REAL; (*SPARE - Spare *)
                            _914 : REAL; (*SPARE - Spare *)
                            _915 : REAL; (*SPARE - Spare *)
                            _916 : REAL; (*SPARE - Spare *)
                            _917 : REAL; (*SPARE - Spare *)
                            _918 : REAL; (*SPARE - Spare *)
                            _919 : REAL; (*SPARE - Spare *)
                            _920 : REAL; (*SPARE - Spare *)
                            _921 : REAL; (*SPARE - Spare *)
                            _922 : REAL; (*SPARE - Spare *)
                            _923 : REAL; (*SPARE - Spare *)
                            _924 : REAL; (*SPARE - Spare *)
                            _925 : REAL; (*SPARE - Spare *)
                            _926 : REAL; (*SPARE - Spare *)
                            _927 : REAL; (*SPARE - Spare *)
                            _928 : REAL; (*SPARE - Spare *)
                            _929 : REAL; (*SPARE - Spare *)
                            _930 : REAL; (*SPARE - Spare *)
                            _931 : REAL; (*SPARE - Spare *)
                            _932 : REAL; (*SPARE - Spare *)
                            _933 : REAL; (*SPARE - Spare *)
                            _934 : REAL; (*SPARE - Spare *)
                            _935 : REAL; (*SPARE - Spare *)
                            _936 : REAL; (*SPARE - Spare *)
                            _937 : REAL; (*SPARE - Spare *)
                            _938 : REAL; (*SPARE - Spare *)
                            _939 : REAL; (*SPARE - Spare *)
                            _940 : REAL; (*SPARE - Spare *)
                            _941 : REAL; (*SPARE - Spare *)
                            _942 : REAL; (*SPARE - Spare *)
                            _943 : REAL; (*SPARE - Spare *)
                            _944 : REAL; (*SPARE - Spare *)
                            _945 : REAL; (*SPARE - Spare *)
                            _946 : REAL; (*SPARE - Spare *)
                            _947 : REAL; (*SPARE - Spare *)
                            _948 : REAL; (*SPARE - Spare *)
                            _949 : REAL; (*SPARE - Spare *)
                            _950 : REAL; (*SPARE - Spare *)
                            _951 : REAL; (*SPARE - Spare *)
                            _952 : REAL; (*SPARE - Spare *)
                            _953 : REAL; (*SPARE - Spare *)
                            _954 : REAL; (*SPARE - Spare *)
                            _955 : REAL; (*SPARE - Spare *)
                            _956 : REAL; (*SPARE - Spare *)
                            _957 : REAL; (*SPARE - Spare *)
                            _958 : REAL; (*SPARE - Spare *)
                            _959 : REAL; (*SPARE - Spare *)
                            _960 : REAL; (*SPARE - Spare *)
                            _961 : REAL; (*SPARE - Spare *)
                            _962 : REAL; (*SPARE - Spare *)
                            _963 : REAL; (*SPARE - Spare *)
                            _964 : REAL; (*SPARE - Spare *)
                            _965 : REAL; (*SPARE - Spare *)
                            _966 : REAL; (*SPARE - Spare *)
                            _967 : REAL; (*SPARE - Spare *)
                            _968 : REAL; (*SPARE - Spare *)
                            _969 : REAL; (*SPARE - Spare *)
                            _970 : REAL; (*SPARE - Spare *)
                            _971 : REAL; (*SPARE - Spare *)
                            _972 : REAL; (*SPARE - Spare *)
                            _973 : REAL; (*SPARE - Spare *)
                            _974 : REAL; (*SPARE - Spare *)
                            _975 : REAL; (*SPARE - Spare *)
                            _976 : REAL; (*SPARE - Spare *)
                            _977 : REAL; (*SPARE - Spare *)
                            _978 : REAL; (*SPARE - Spare *)
                            _979 : REAL; (*SPARE - Spare *)
                            _980 : REAL; (*SPARE - Spare *)
                            _981 : REAL; (*SPARE - Spare *)
                            _982 : REAL; (*SPARE - Spare *)
                            _983 : REAL; (*SPARE - Spare *)
                            _984 : REAL; (*SPARE - Spare *)
                            _985 : REAL; (*SPARE - Spare *)
                            _986 : REAL; (*SPARE - Spare *)
                            _987 : REAL; (*SPARE - Spare *)
                            _988 : REAL; (*SPARE - Spare *)
                            _989 : REAL; (*SPARE - Spare *)
                            _990 : REAL; (*SPARE - Spare *)
                            _991 : REAL; (*SPARE - Spare *)
                            _992 : REAL; (*SPARE - Spare *)
                            _993 : REAL; (*SPARE - Spare *)
                            _994 : REAL; (*SPARE - Spare *)
                            _995 : REAL; (*SPARE - Spare *)
                            _996 : REAL; (*SPARE - Spare *)
                            _997 : REAL; (*SPARE - Spare *)
                            _998 : REAL; (*SPARE - Spare *)
                            _999 : REAL; (*SPARE - Spare *)
        END_STRUCT;
END_TYPE
