(*HMI_PAC_1 Database for Filler PLC*)
(*Author = UTERF*)
(*DB Version : 0.11*)
(*File Version : 3,17*)

TYPE
        HMI_PAC_1_Type:     STRUCT
                            _000 : INT; (*MACHINE - Step from Container Block#1 to Filler Presence *)
                            _001 : INT; (*MACHINE - Step from Machine Inlet to Filler Presence *)
                            _002 : INT; (*MACHINE - Step from Container Block to Outlet Machine *)
                            _003 : INT; (*MACHINE - Step from Container Block#2 to Filler Presence *)
                            _004 : INT; (*MACHINE - Filling After Containers Release *)
                            _005 : INT; (*MACHINE - Steps from machine inlet to carousel outlet reject command *)
                            _006 : INT; (*MACHINE - Steps from machine inlet to carousel outlet control sensor *)
                            _007 : INT; (*MACHINE - Step from machine inlet to Containers Shower Command *)
                            _008 : INT; (*MACHINE - Step from machine inlet to Containers Expulsor Command *)
                            _009 : INT; (*MACHINE - Steps from container block to machine inlet presence sensor *)
                            _010 : INT; (*MACHINE - Spare *)
                            _011 : INT; (*MACHINE - Spare *)
                            _012 : INT; (*MACHINE - Spare *)
                            _013 : INT; (*MACHINE - Step from machine inlet to Containers Cap Drying Blow *)
                            _014 : INT; (*MACHINE - Step from machine inlet to Machine Outlet Control (Videojet) *)
                            _015 : INT; (*MACHINE - Steps from machine inlet to Doser inlet tangency  *)
                            _016 : INT; (*MACHINE - Steps from machine inlet to Rinser Outlet (208DSF) *)
                            _017 : INT; (*MACHINE - Steps from machine inlet to Rinser tangency nozzle *)
                            _018 : INT; (*MACHINE - Steps from machine inlet to doser outlet control sensor *)
                            _019 : INT; (*MACHINE - Step from Filler Presence Closing unit Presence *)
                            _020 : INT; (*MACHINE - Step from Machine Inlet to Closing unit Inlet Tangency *)
                            _021 : INT; (*MACHINE - Offset synchro head in tangent on Capper Head #1 sensor *)
                            _022 : INT; (*MACHINE - Offset synchro Container Mold Number *)
                            _023 : INT; (*MACHINE - Step from machine inlet to rinsing unit inlet tangency *)
                            _024 : INT; (*MACHINE - Offset synchro head in tangent on Crowner Head #1 sensor *)
                            _025 : INT; (*MACHINE - Offset synchro head in tangent on Doser Head #1 sensor *)
                            _026 : INT; (*MACHINE - Spare *)
                            _027 : INT; (*MACHINE - Spare *)
                            _028 : INT; (*MACHINE - Spare *)
                            _029 : INT; (*MACHINE - Spare *)
                            _030 : INT; (*MACHINE - Spare *)
                            _031 : INT; (*MACHINE - Spare *)
                            _032 : INT; (*MACHINE - Spare *)
                            _033 : INT; (*MACHINE - Spare *)
                            _034 : INT; (*MACHINE - Spare *)
                            _035 : INT; (*MACHINE - Spare *)
                            _036 : INT; (*MACHINE - Spare *)
                            _037 : INT; (*MACHINE - Spare *)
                            _038 : INT; (*MACHINE - Spare *)
                            _039 : INT; (*MACHINE - Spare *)
                            _040 : INT; (*MACHINE - Spare *)
                            _041 : INT; (*MACHINE - Spare *)
                            _042 : INT; (*MACHINE - Spare *)
                            _043 : INT; (*MACHINE - Spare *)
                            _044 : INT; (*MACHINE - Spare *)
                            _045 : INT; (*MACHINE - Machine inlet star gripper number *)
                            _046 : INT; (*MACHINE - Spare *)
                            _047 : INT; (*MACHINE - Spare *)
                            _048 : INT; (*MACHINE - Spare *)
                            _049 : INT; (*MACHINE - Spare *)
                            _050 : INT; (*MACHINE - Spare *)
                            _051 : INT; (*MACHINE - Spare *)
                            _052 : INT; (*MACHINE - Spare *)
                            _053 : INT; (*MACHINE - Spare *)
                            _054 : INT; (*MACHINE - Spare *)
                            _055 : INT; (*MACHINE - Spare *)
                            _056 : INT; (*MACHINE - Spare *)
                            _057 : INT; (*MACHINE - Spare *)
                            _058 : INT; (*MACHINE - Spare *)
                            _059 : INT; (*MACHINE - Spare *)
                            _060 : INT; (*MACHINE - Spare *)
                            _061 : INT; (*MACHINE - Spare *)
                            _062 : INT; (*MACHINE - Spare *)
                            _063 : INT; (*MACHINE - Spare *)
                            _064 : INT; (*MACHINE - Spare *)
                            _065 : INT; (*MACHINE - Spare *)
                            _066 : INT; (*MACHINE - Spare *)
                            _067 : INT; (*MACHINE - Spare *)
                            _068 : INT; (*MACHINE - Spare *)
                            _069 : INT; (*MACHINE - Spare *)
                            _070 : INT; (*MACHINE - Labeler marker: Offset synchro filling valve number *)
                            _071 : INT; (*MACHINE - Labeler marker: Offset synchro capping head number *)
                            _072 : INT; (*MACHINE - Spare *)
                            _073 : INT; (*MACHINE - Spare *)
                            _074 : INT; (*MACHINE - Spare *)
                            _075 : INT; (*MACHINE - Spare *)
                            _076 : INT; (*MACHINE - Spare *)
                            _077 : INT; (*MACHINE - Spare *)
                            _078 : INT; (*MACHINE - Spare *)
                            _079 : INT; (*MACHINE - Spare *)
                            _080 : INT; (*MACHINE - Spare *)
                            _081 : INT; (*MACHINE - Spare *)
                            _082 : INT; (*MACHINE - Spare *)
                            _083 : INT; (*MACHINE - Spare *)
                            _084 : INT; (*MACHINE - Spare *)
                            _085 : INT; (*MACHINE - Spare *)
                            _086 : INT; (*MACHINE - Spare *)
                            _087 : INT; (*MACHINE - Spare *)
                            _088 : INT; (*MACHINE - Spare *)
                            _089 : INT; (*MACHINE - Spare *)
                            _090 : INT; (*MACHINE - Spare *)
                            _091 : INT; (*MACHINE - Spare *)
                            _092 : INT; (*MACHINE - Spare *)
                            _093 : INT; (*MACHINE - Spare *)
                            _094 : INT; (*MACHINE - Spare *)
                            _095 : INT; (*MACHINE - Spare *)
                            _096 : INT; (*MACHINE - Spare *)
                            _097 : INT; (*MACHINE - Spare *)
                            _098 : INT; (*MACHINE - Spare *)
                            _099 : INT; (*MACHINE - Spare *)
                            _100 : INT; (*FILLER - Filling Valves Number *)
                            _101 : INT; (*FILLER - Step from Machine Inlet to Filling Valve n°1 *)
                            _102 : INT; (*FILLER - Step from Machine Inlet to Opening Command n°1 *)
                            _103 : INT; (*FILLER - Step from Machine Inlet to Opening Command n°2 *)
                            _104 : INT; (*FILLER - Step from Machine Inlet to Tube Purge Command *)
                            _105 : INT; (*FILLER - Step from Machine Inlet to Unhook Recyrcle Command *)
                            _106 : INT; (*FILLER - Step from Machine Inlet to Hook Recyrcle Command *)
                            _107 : INT; (*FILLER - Step from Machine Inlet to Safety Cam Command *)
                            _108 : INT; (*FILLER - Step from Machine Inlet to Rol Safety Control *)
                            _109 : INT; (*FILLER - Spare *)
                            _110 : INT; (*FILLER - Step from Machine Inlet to Preinjction Skate *)
                            _111 : INT; (*FILLER - Step from Machine Inlet to Decompression Skate n°1 *)
                            _112 : INT; (*FILLER - Number of Step Activation Decompression Skate n°1 *)
                            _113 : INT; (*FILLER - Step from Machine Inlet to Decompression Skate n°2 *)
                            _114 : INT; (*FILLER - Number of Step Activation Decompression Skate n°2 *)
                            _115 : INT; (*FILLER - Step from Machine Inlet to Preclosing Command *)
                            _116 : INT; (*FILLER - Spare *)
                            _117 : INT; (*FILLER - Step from Machine Inlet to Broken#1 Sensor Control *)
                            _118 : INT; (*FILLER - Step from Machine Inlet to Broken#2 Sensor Control *)
                            _119 : INT; (*FILLER - Spare *)
                            _120 : INT; (*FILLER - Step from Machine Inlet to Start Washing Valve n°1 *)
                            _121 : INT; (*FILLER - Duration in steps of washing valve n°1 activation *)
                            _122 : INT; (*FILLER - Step from Machine Inlet to Start Washing Valve n°2 *)
                            _123 : INT; (*FILLER - Duration in steps of washing valve n°2 activation *)
                            _124 : INT; (*FILLER - Step from Machine Inlet to Start Washing Valve n°3 *)
                            _125 : INT; (*FILLER - Duration in steps of washing valve n°3 activation *)
                            _126 : INT; (*FILLER - Step from Machine Inlet to Start Washing Valve n°4 *)
                            _127 : INT; (*FILLER - Duration in steps of washing valve n°4 activation *)
                            _128 : INT; (*FILLER - Step from Can Block to End Washing Valves *)
                            _129 : INT; (*FILLER - Rinsing valve in tangency when access platform in position *)
                            _130 : INT; (*FILLER - Filling valve in tangency when access platform in position *)
                            _131 : INT; (*FILLER - Capping head in tangency when greasing connection in position *)
                            _132 : INT; (*FILLER - Steps from carousel inlet tangency to containers burst ispection *)
                            _133 : INT; (*FILLER - Crowner head in tangency when lifting position is reached *)
                            _134 : INT; (*FILLER - Capper head in tangency when lifting position is reached *)
                            _135 : INT; (*FILLER - Spare *)
                            _136 : INT; (*FILLER - Spare *)
                            _137 : INT; (*FILLER - Spare *)
                            _138 : INT; (*FILLER - Spare *)
                            _139 : INT; (*FILLER - Spare *)
                            _140 : INT; (*FILLER - Spare *)
                            _141 : INT; (*FILLER - Spare *)
                            _142 : INT; (*FILLER - Spare *)
                            _143 : INT; (*FILLER - Spare *)
                            _144 : INT; (*FILLER - Spare *)
                            _145 : INT; (*FILLER - Carousel inlet star gripper number *)
                            _146 : INT; (*FILLER - Carousel outlet star gripper number *)
                            _147 : INT; (*FILLER - Spare *)
                            _148 : INT; (*FILLER - Spare *)
                            _149 : INT; (*FILLER - Spare *)
                            _150 : INT; (*FILLER - Steps from preforms\containers inlet to carousel inlet tangency *)
                            _151 : INT; (*FILLER - FMC Get Burst *)
                            _152 : INT; (*FILLER - FMC Get Data *)
                            _153 : INT; (*FILLER - Spare *)
                            _154 : INT; (*FILLER - Spare *)
                            _155 : INT; (*FILLER - Spare *)
                            _156 : INT; (*FILLER - Spare *)
                            _157 : INT; (*FILLER - Spare *)
                            _158 : INT; (*FILLER - Spare *)
                            _159 : INT; (*FILLER - Spare *)
                            _160 : INT; (*FILLER - Spare *)
                            _161 : INT; (*FILLER - Spare *)
                            _162 : INT; (*FILLER - Spare *)
                            _163 : INT; (*FILLER - Spare *)
                            _164 : INT; (*FILLER - Spare *)
                            _165 : INT; (*FILLER - Spare *)
                            _166 : INT; (*FILLER - Spare *)
                            _167 : INT; (*FILLER - Spare *)
                            _168 : INT; (*FILLER - Spare *)
                            _169 : INT; (*FILLER - Spare *)
                            _170 : INT; (*FILLER - Spare *)
                            _171 : INT; (*FILLER - Spare *)
                            _172 : INT; (*FILLER - Spare *)
                            _173 : INT; (*FILLER - Spare *)
                            _174 : INT; (*FILLER - Spare *)
                            _175 : INT; (*FILLER - Spare *)
                            _176 : INT; (*FILLER - Spare *)
                            _177 : INT; (*FILLER - Spare *)
                            _178 : INT; (*FILLER - Spare *)
                            _179 : INT; (*FILLER - Spare *)
                            _180 : INT; (*FILLER - Spare *)
                            _181 : INT; (*FILLER - Spare *)
                            _182 : INT; (*FILLER - Spare *)
                            _183 : INT; (*FILLER - Spare *)
                            _184 : INT; (*FILLER - Spare *)
                            _185 : INT; (*FILLER - Spare *)
                            _186 : INT; (*FILLER - Spare *)
                            _187 : INT; (*FILLER - Spare *)
                            _188 : INT; (*FILLER - Spare *)
                            _189 : INT; (*FILLER - Spare *)
                            _190 : INT; (*FILLER - Spare *)
                            _191 : INT; (*FILLER - Spare *)
                            _192 : INT; (*FILLER - Spare *)
                            _193 : INT; (*FILLER - Spare *)
                            _194 : INT; (*FILLER - Spare *)
                            _195 : INT; (*FILLER - Spare *)
                            _196 : INT; (*FILLER - Spare *)
                            _197 : INT; (*FILLER - Spare *)
                            _198 : INT; (*FILLER - Spare *)
                            _199 : INT; (*FILLER - Spare *)
                            _200 : INT; (*RINSER - Nozzle Number *)
                            _201 : INT; (*RINSER - Step from Machine Inlet to Start Treatment n°1 *)
                            _202 : INT; (*RINSER - Number of Step Activation Treatment n°1 *)
                            _203 : INT; (*RINSER - Step from Machine Inlet to Start Treatment n°2 *)
                            _204 : INT; (*RINSER - Number of Step Activation Treatment n°2 *)
                            _205 : INT; (*RINSER - Step from Machine Inlet to Start Treatment n°3 *)
                            _206 : INT; (*RINSER - Number of Step Activation Treatment n°3 *)
                            _207 : INT; (*RINSER - Step from Machine Inlet to NoBottle-NoSpray Command n°1 *)
                            _208 : INT; (*RINSER - Step from Machine Inlet to NoBottle-NoSpray Command n°2 *)
                            _209 : INT; (*RINSER - Step from Machine Inlet to NoBottle-NoSpray Command n°3 *)
                            _210 : INT; (*RINSER - Step from Machine Inlet to Spray Check Nozzle n°1 *)
                            _211 : INT; (*RINSER - Step from Machine Inlet to Filler Preclosing Command *)
                            _212 : INT; (*RINSER - Step from Nozzle in Tangency to Rinser insercion Control *)
                            _213 : INT; (*RINSER - Step from Machine Inlet to Rinser Air Continous Control *)
                            _214 : INT; (*RINSER - Step from Machine Inlet to Rinser Water Continous Control *)
                            _215 : INT; (*RINSER - Step Adjustment for Rinser Bypassed *)
                            _216 : INT; (*RINSER - Spare *)
                            _217 : INT; (*RINSER - Spare *)
                            _218 : INT; (*RINSER - Spare *)
                            _219 : INT; (*RINSER - Offset synchro rinsing valve actual in tangent  *)
                            _220 : INT; (*RINSER - Rinsing valve in tangency when access platform in position *)
                            _221 : INT; (*RINSER - Spare *)
                            _222 : INT; (*RINSER - Spare *)
                            _223 : INT; (*RINSER - Spare *)
                            _224 : INT; (*RINSER - Spare *)
                            _225 : INT; (*RINSER - Spare *)
                            _226 : INT; (*RINSER - Spare *)
                            _227 : INT; (*RINSER - Spare *)
                            _228 : INT; (*RINSER - Spare *)
                            _229 : INT; (*RINSER - Spare *)
                            _230 : INT; (*RINSER - Spare *)
                            _231 : INT; (*RINSER - Spare *)
                            _232 : INT; (*RINSER - Spare *)
                            _233 : INT; (*RINSER - Spare *)
                            _234 : INT; (*RINSER - Spare *)
                            _235 : INT; (*RINSER - Spare *)
                            _236 : INT; (*RINSER - Spare *)
                            _237 : INT; (*RINSER - Spare *)
                            _238 : INT; (*RINSER - Spare *)
                            _239 : INT; (*RINSER - Spare *)
                            _240 : INT; (*RINSER - Spare *)
                            _241 : INT; (*RINSER - Spare *)
                            _242 : INT; (*RINSER - Spare *)
                            _243 : INT; (*RINSER - Spare *)
                            _244 : INT; (*RINSER - Spare *)
                            _245 : INT; (*RINSER - Rinser inlet star gripper number *)
                            _246 : INT; (*RINSER - Rinser outlet star gripper number *)
                            _247 : INT; (*RINSER - Spare *)
                            _248 : INT; (*RINSER - Spare *)
                            _249 : INT; (*RINSER - Spare *)
                            _250 : INT; (*RINSER - Spare *)
                            _251 : INT; (*RINSER - Spare *)
                            _252 : INT; (*RINSER - Spare *)
                            _253 : INT; (*RINSER - Spare *)
                            _254 : INT; (*RINSER - Spare *)
                            _255 : INT; (*RINSER - Spare *)
                            _256 : INT; (*RINSER - Spare *)
                            _257 : INT; (*RINSER - Spare *)
                            _258 : INT; (*RINSER - Spare *)
                            _259 : INT; (*RINSER - Spare *)
                            _260 : INT; (*RINSER - Spare *)
                            _261 : INT; (*RINSER - Spare *)
                            _262 : INT; (*RINSER - Spare *)
                            _263 : INT; (*RINSER - Spare *)
                            _264 : INT; (*RINSER - Spare *)
                            _265 : INT; (*RINSER - Spare *)
                            _266 : INT; (*RINSER - Spare *)
                            _267 : INT; (*RINSER - Spare *)
                            _268 : INT; (*RINSER - Spare *)
                            _269 : INT; (*RINSER - Spare *)
                            _270 : INT; (*RINSER - Spare *)
                            _271 : INT; (*RINSER - Spare *)
                            _272 : INT; (*RINSER - Spare *)
                            _273 : INT; (*RINSER - Spare *)
                            _274 : INT; (*RINSER - Spare *)
                            _275 : INT; (*RINSER - Spare *)
                            _276 : INT; (*RINSER - Spare *)
                            _277 : INT; (*RINSER - Spare *)
                            _278 : INT; (*RINSER - Spare *)
                            _279 : INT; (*RINSER - Spare *)
                            _280 : INT; (*RINSER - Spare *)
                            _281 : INT; (*RINSER - Spare *)
                            _282 : INT; (*RINSER - Spare *)
                            _283 : INT; (*RINSER - Spare *)
                            _284 : INT; (*RINSER - Spare *)
                            _285 : INT; (*RINSER - Spare *)
                            _286 : INT; (*RINSER - Spare *)
                            _287 : INT; (*RINSER - Spare *)
                            _288 : INT; (*RINSER - Spare *)
                            _289 : INT; (*RINSER - Spare *)
                            _290 : INT; (*RINSER - Spare *)
                            _291 : INT; (*RINSER - Spare *)
                            _292 : INT; (*RINSER - Spare *)
                            _293 : INT; (*RINSER - Spare *)
                            _294 : INT; (*RINSER - Spare *)
                            _295 : INT; (*RINSER - Spare *)
                            _296 : INT; (*RINSER - Spare *)
                            _297 : INT; (*RINSER - Spare *)
                            _298 : INT; (*RINSER - Spare *)
                            _299 : INT; (*RINSER - Spare *)
                            _300 : INT; (*CROWNER - Heads Number *)
                            _301 : INT; (*CROWNER - Step from Machine Inlet to Crowner Head n°1 *)
                            _302 : INT; (*CROWNER - Step from Machine Inlet to Crowner Air Valve Command *)
                            _303 : INT; (*CROWNER - Step from Machine Inlet to Crowner Opening Channel n°1 *)
                            _304 : INT; (*CROWNER - Step from Machine Inlet to Crowner Star Crown Control *)
                            _305 : INT; (*CROWNER - Step for Change Crowner Channel n°1 to Crowner Channel n°2 *)
                            _306 : INT; (*CROWNER - Step for Change Crowner Channel n°2 to Crowner Channel n°1 *)
                            _307 : INT; (*CROWNER - Step from Machine Inlet to Crowner Broken Sensor Control *)
                            _308 : INT; (*CROWNER - Spare *)
                            _309 : INT; (*CROWNER - Spare *)
                            _310 : INT; (*CROWNER - Spare *)
                            _311 : INT; (*CROWNER - Spare *)
                            _312 : INT; (*CROWNER - Spare *)
                            _313 : INT; (*CROWNER - Spare *)
                            _314 : INT; (*CROWNER - Spare *)
                            _315 : INT; (*CROWNER - Spare *)
                            _316 : INT; (*CROWNER - Spare *)
                            _317 : INT; (*CROWNER - Spare *)
                            _318 : INT; (*CROWNER - Spare *)
                            _319 : INT; (*CROWNER - Spare *)
                            _320 : INT; (*CROWNER - Spare *)
                            _321 : INT; (*CROWNER - Spare *)
                            _322 : INT; (*CROWNER - Spare *)
                            _323 : INT; (*CROWNER - Spare *)
                            _324 : INT; (*CROWNER - Spare *)
                            _325 : INT; (*CROWNER - Spare *)
                            _326 : INT; (*CROWNER - Spare *)
                            _327 : INT; (*CROWNER - Spare *)
                            _328 : INT; (*CROWNER - Spare *)
                            _329 : INT; (*CROWNER - Spare *)
                            _330 : INT; (*CROWNER - Spare *)
                            _331 : INT; (*CROWNER - Spare *)
                            _332 : INT; (*CROWNER - Spare *)
                            _333 : INT; (*CROWNER - Spare *)
                            _334 : INT; (*CROWNER - Spare *)
                            _335 : INT; (*CROWNER - Spare *)
                            _336 : INT; (*CROWNER - Spare *)
                            _337 : INT; (*CROWNER - Spare *)
                            _338 : INT; (*CROWNER - Spare *)
                            _339 : INT; (*CROWNER - Spare *)
                            _340 : INT; (*CROWNER - Spare *)
                            _341 : INT; (*CROWNER - Spare *)
                            _342 : INT; (*CROWNER - Spare *)
                            _343 : INT; (*CROWNER - Spare *)
                            _344 : INT; (*CROWNER - Spare *)
                            _345 : INT; (*CROWNER - Spare *)
                            _346 : INT; (*CROWNER - Spare *)
                            _347 : INT; (*CROWNER - Spare *)
                            _348 : INT; (*CROWNER - Spare *)
                            _349 : INT; (*CROWNER - Spare *)
                            _350 : INT; (*CROWNER - Spare *)
                            _351 : INT; (*CROWNER - Spare *)
                            _352 : INT; (*CROWNER - Spare *)
                            _353 : INT; (*CROWNER - Spare *)
                            _354 : INT; (*CROWNER - Spare *)
                            _355 : INT; (*CROWNER - Spare *)
                            _356 : INT; (*CROWNER - Spare *)
                            _357 : INT; (*CROWNER - Spare *)
                            _358 : INT; (*CROWNER - Spare *)
                            _359 : INT; (*CROWNER - Spare *)
                            _360 : INT; (*CROWNER - Spare *)
                            _361 : INT; (*CROWNER - Spare *)
                            _362 : INT; (*CROWNER - Spare *)
                            _363 : INT; (*CROWNER - Spare *)
                            _364 : INT; (*CROWNER - Spare *)
                            _365 : INT; (*CROWNER - Spare *)
                            _366 : INT; (*CROWNER - Spare *)
                            _367 : INT; (*CROWNER - Spare *)
                            _368 : INT; (*CROWNER - Spare *)
                            _369 : INT; (*CROWNER - Spare *)
                            _370 : INT; (*CROWNER - Spare *)
                            _371 : INT; (*CROWNER - Spare *)
                            _372 : INT; (*CROWNER - Spare *)
                            _373 : INT; (*CROWNER - Spare *)
                            _374 : INT; (*CROWNER - Spare *)
                            _375 : INT; (*CROWNER - Spare *)
                            _376 : INT; (*CROWNER - Spare *)
                            _377 : INT; (*CROWNER - Spare *)
                            _378 : INT; (*CROWNER - Spare *)
                            _379 : INT; (*CROWNER - Spare *)
                            _380 : INT; (*CROWNER - Spare *)
                            _381 : INT; (*CROWNER - Spare *)
                            _382 : INT; (*CROWNER - Spare *)
                            _383 : INT; (*CROWNER - Spare *)
                            _384 : INT; (*CROWNER - Spare *)
                            _385 : INT; (*CROWNER - Spare *)
                            _386 : INT; (*CROWNER - Spare *)
                            _387 : INT; (*CROWNER - Spare *)
                            _388 : INT; (*CROWNER - Spare *)
                            _389 : INT; (*CROWNER - Spare *)
                            _390 : INT; (*CROWNER - Spare *)
                            _391 : INT; (*CROWNER - Spare *)
                            _392 : INT; (*CROWNER - Spare *)
                            _393 : INT; (*CROWNER - Spare *)
                            _394 : INT; (*CROWNER - Spare *)
                            _395 : INT; (*CROWNER - Spare *)
                            _396 : INT; (*CROWNER - Spare *)
                            _397 : INT; (*CROWNER - Spare *)
                            _398 : INT; (*CROWNER - Spare *)
                            _399 : INT; (*CROWNER - Spare *)
                            _400 : INT; (*CAPPER - Heads Number *)
                            _401 : INT; (*CAPPER - Steps from machine inlet to capper air activation *)
                            _402 : INT; (*CAPPER - Steps from machine inlet to capper cap release *)
                            _403 : INT; (*CAPPER - Steps from machine inlet to capper cap release control *)
                            _404 : INT; (*CAPPER - Step from Machine Inlet to Capper#2 Air Valve Command *)
                            _405 : INT; (*CAPPER - Step from Machine Inlet to Capper#2 Opening Channel *)
                            _406 : INT; (*CAPPER - Step from Machine Inlet to Capper#2 Star Caps Control *)
                            _407 : INT; (*CAPPER - Step from Machine Inlet to Capper#3 Air Valve Command *)
                            _408 : INT; (*CAPPER - Step from Machine Inlet to Capper#3 Opening Channel *)
                            _409 : INT; (*CAPPER - Step from Machine Inlet to Capper#3 Star Caps Control *)
                            _410 : INT; (*CAPPER - Step from Machine Inlet to Bottle Neck Whashing Valve Command *)
                            _411 : INT; (*CAPPER - Number of Step Activation Bottle Neck Whashing Valve *)
                            _412 : INT; (*CAPPER - Step from Machine Inlet to End Capper Head Washing *)
                            _413 : INT; (*CAPPER - Step from Machine Inlet to Capped Bottle Detect *)
                            _414 : INT; (*CAPPER - Spare *)
                            _415 : INT; (*CAPPER - Step from Machine Inlet to Head Data Read (Arol Equatorque) *)
                            _416 : INT; (*CAPPER - Steps from preform block to request of caps to cap treatment  *)
                            _417 : INT; (*CAPPER - Step delay to start request of caps to cap treatment *)
                            _418 : INT; (*CAPPER - Step offset to stop request of caps to cap treatment *)
                            _419 : INT; (*CAPPER - Capper Outlet Star Grip Number *)
                            _420 : INT; (*CAPPER - Dryer outlet star gripper number *)
                            _421 : INT; (*CAPPER - Spare *)
                            _422 : INT; (*CAPPER - Camma High Position [mm*10] *)
                            _423 : INT; (*CAPPER - Camma Low Position [mm*10] *)
                            _424 : INT; (*CAPPER - Spare *)
                            _425 : INT; (*CAPPER - Spare *)
                            _426 : INT; (*CAPPER - Spare *)
                            _427 : INT; (*CAPPER - Spare *)
                            _428 : INT; (*CAPPER - Spare *)
                            _429 : INT; (*CAPPER - Spare *)
                            _430 : INT; (*CAPPER - Spare *)
                            _431 : INT; (*CAPPER - Spare *)
                            _432 : INT; (*CAPPER - Spare *)
                            _433 : INT; (*CAPPER - Spare *)
                            _434 : INT; (*CAPPER - Spare *)
                            _435 : INT; (*CAPPER - Spare *)
                            _436 : INT; (*CAPPER - Spare *)
                            _437 : INT; (*CAPPER - Spare *)
                            _438 : INT; (*CAPPER - Spare *)
                            _439 : INT; (*CAPPER - Spare *)
                            _440 : INT; (*CAPPER - Spare *)
                            _441 : INT; (*CAPPER - Spare *)
                            _442 : INT; (*CAPPER - Spare *)
                            _443 : INT; (*CAPPER - Spare *)
                            _444 : INT; (*CAPPER - Spare *)
                            _445 : INT; (*CAPPER - Spare *)
                            _446 : INT; (*CAPPER - Spare *)
                            _447 : INT; (*CAPPER - Spare *)
                            _448 : INT; (*CAPPER - Spare *)
                            _449 : INT; (*CAPPER - Spare *)
                            _450 : INT; (*CAPPER - Spare *)
                            _451 : INT; (*CAPPER - Spare *)
                            _452 : INT; (*CAPPER - Spare *)
                            _453 : INT; (*CAPPER - Spare *)
                            _454 : INT; (*CAPPER - Spare *)
                            _455 : INT; (*CAPPER - Spare *)
                            _456 : INT; (*CAPPER - Spare *)
                            _457 : INT; (*CAPPER - Spare *)
                            _458 : INT; (*CAPPER - Spare *)
                            _459 : INT; (*CAPPER - Spare *)
                            _460 : INT; (*CAPPER - Spare *)
                            _461 : INT; (*CAPPER - Spare *)
                            _462 : INT; (*CAPPER - Spare *)
                            _463 : INT; (*CAPPER - Spare *)
                            _464 : INT; (*CAPPER - Spare *)
                            _465 : INT; (*CAPPER - Spare *)
                            _466 : INT; (*CAPPER - Spare *)
                            _467 : INT; (*CAPPER - Spare *)
                            _468 : INT; (*CAPPER - Spare *)
                            _469 : INT; (*CAPPER - Spare *)
                            _470 : INT; (*CAPPER - Spare *)
                            _471 : INT; (*CAPPER - Spare *)
                            _472 : INT; (*CAPPER - Spare *)
                            _473 : INT; (*CAPPER - Spare *)
                            _474 : INT; (*CAPPER - Spare *)
                            _475 : INT; (*CAPPER - Spare *)
                            _476 : INT; (*CAPPER - Spare *)
                            _477 : INT; (*CAPPER - Spare *)
                            _478 : INT; (*CAPPER - Spare *)
                            _479 : INT; (*CAPPER - Spare *)
                            _480 : INT; (*CAPPER - Spare *)
                            _481 : INT; (*CAPPER - Spare *)
                            _482 : INT; (*CAPPER - Spare *)
                            _483 : INT; (*CAPPER - Spare *)
                            _484 : INT; (*CAPPER - Spare *)
                            _485 : INT; (*CAPPER - Spare *)
                            _486 : INT; (*CAPPER - Spare *)
                            _487 : INT; (*CAPPER - Spare *)
                            _488 : INT; (*CAPPER - Spare *)
                            _489 : INT; (*CAPPER - Spare *)
                            _490 : INT; (*CAPPER - Spare *)
                            _491 : INT; (*CAPPER - Spare *)
                            _492 : INT; (*CAPPER - Spare *)
                            _493 : INT; (*CAPPER - Spare *)
                            _494 : INT; (*CAPPER - Spare *)
                            _495 : INT; (*CAPPER - Spare *)
                            _496 : INT; (*CAPPER - Spare *)
                            _497 : INT; (*CAPPER - Spare *)
                            _498 : INT; (*CAPPER - Spare *)
                            _499 : INT; (*CAPPER - Spare *)
                            _500 : INT; (*PulpDoser - Doser Filling Valves Number *)
                            _501 : INT; (*PulpDoser - Step from Machine Inlet to Opening Command n°1 *)
                            _502 : INT; (*PulpDoser - Step from Machine Inlet to Hema Filling Valve n°1 *)
                            _503 : INT; (*PulpDoser - Step from Machine Inlet to Opening Command n°2 (High Speed) *)
                            _504 : INT; (*PulpDoser - Step from Machine Inlet to Hema Neck Washing *)
                            _505 : INT; (*PulpDoser - Step Adjustment for Doser Bypassed *)
                            _506 : INT; (*PulpDoser - Spare *)
                            _507 : INT; (*PulpDoser - Spare *)
                            _508 : INT; (*PulpDoser - Spare *)
                            _509 : INT; (*PulpDoser - Spare *)
                            _510 : INT; (*PulpDoser - Doser Star Grip Number *)
                            _511 : INT; (*PulpDoser - Spare *)
                            _512 : INT; (*PulpDoser - Spare *)
                            _513 : INT; (*PulpDoser - Spare *)
                            _514 : INT; (*PulpDoser - Spare *)
                            _515 : INT; (*PulpDoser - Spare *)
                            _516 : INT; (*PulpDoser - Spare *)
                            _517 : INT; (*PulpDoser - Spare *)
                            _518 : INT; (*PulpDoser - Spare *)
                            _519 : INT; (*PulpDoser - Spare *)
                            _520 : INT; (*PulpDoser - Spare *)
                            _521 : INT; (*PulpDoser - Spare *)
                            _522 : INT; (*PulpDoser - Spare *)
                            _523 : INT; (*PulpDoser - Spare *)
                            _524 : INT; (*PulpDoser - Spare *)
                            _525 : INT; (*PulpDoser - Spare *)
                            _526 : INT; (*PulpDoser - Spare *)
                            _527 : INT; (*PulpDoser - Spare *)
                            _528 : INT; (*PulpDoser - Spare *)
                            _529 : INT; (*PulpDoser - Spare *)
                            _530 : INT; (*PulpDoser - Spare *)
                            _531 : INT; (*PulpDoser - Spare *)
                            _532 : INT; (*PulpDoser - Spare *)
                            _533 : INT; (*PulpDoser - Spare *)
                            _534 : INT; (*PulpDoser - Spare *)
                            _535 : INT; (*PulpDoser - Spare *)
                            _536 : INT; (*PulpDoser - Spare *)
                            _537 : INT; (*PulpDoser - Spare *)
                            _538 : INT; (*PulpDoser - Spare *)
                            _539 : INT; (*PulpDoser - Spare *)
                            _540 : INT; (*PulpDoser - Spare *)
                            _541 : INT; (*PulpDoser - Spare *)
                            _542 : INT; (*PulpDoser - Spare *)
                            _543 : INT; (*PulpDoser - Spare *)
                            _544 : INT; (*PulpDoser - Spare *)
                            _545 : INT; (*PulpDoser - Spare *)
                            _546 : INT; (*PulpDoser - Spare *)
                            _547 : INT; (*PulpDoser - Spare *)
                            _548 : INT; (*PulpDoser - Spare *)
                            _549 : INT; (*PulpDoser - Spare *)
                            _550 : INT; (*PulpDoser - Spare *)
                            _551 : INT; (*PulpDoser - Spare *)
                            _552 : INT; (*PulpDoser - Spare *)
                            _553 : INT; (*PulpDoser - Spare *)
                            _554 : INT; (*PulpDoser - Spare *)
                            _555 : INT; (*PulpDoser - Spare *)
                            _556 : INT; (*PulpDoser - Spare *)
                            _557 : INT; (*PulpDoser - Spare *)
                            _558 : INT; (*PulpDoser - Spare *)
                            _559 : INT; (*PulpDoser - Spare *)
                            _560 : INT; (*PulpDoser - Spare *)
                            _561 : INT; (*PulpDoser - Spare *)
                            _562 : INT; (*PulpDoser - Spare *)
                            _563 : INT; (*PulpDoser - Spare *)
                            _564 : INT; (*PulpDoser - Spare *)
                            _565 : INT; (*PulpDoser - Spare *)
                            _566 : INT; (*PulpDoser - Spare *)
                            _567 : INT; (*PulpDoser - Spare *)
                            _568 : INT; (*PulpDoser - Spare *)
                            _569 : INT; (*PulpDoser - Spare *)
                            _570 : INT; (*PulpDoser - Spare *)
                            _571 : INT; (*PulpDoser - Spare *)
                            _572 : INT; (*PulpDoser - Spare *)
                            _573 : INT; (*PulpDoser - Spare *)
                            _574 : INT; (*PulpDoser - Spare *)
                            _575 : INT; (*PulpDoser - Spare *)
                            _576 : INT; (*PulpDoser - Spare *)
                            _577 : INT; (*PulpDoser - Spare *)
                            _578 : INT; (*PulpDoser - Spare *)
                            _579 : INT; (*PulpDoser - Spare *)
                            _580 : INT; (*PulpDoser - Spare *)
                            _581 : INT; (*PulpDoser - Spare *)
                            _582 : INT; (*PulpDoser - Spare *)
                            _583 : INT; (*PulpDoser - Spare *)
                            _584 : INT; (*PulpDoser - Spare *)
                            _585 : INT; (*PulpDoser - Spare *)
                            _586 : INT; (*PulpDoser - Spare *)
                            _587 : INT; (*PulpDoser - Spare *)
                            _588 : INT; (*PulpDoser - Spare *)
                            _589 : INT; (*PulpDoser - Spare *)
                            _590 : INT; (*PulpDoser - Spare *)
                            _591 : INT; (*PulpDoser - Spare *)
                            _592 : INT; (*PulpDoser - Spare *)
                            _593 : INT; (*PulpDoser - Spare *)
                            _594 : INT; (*PulpDoser - Spare *)
                            _595 : INT; (*PulpDoser - Spare *)
                            _596 : INT; (*PulpDoser - Spare *)
                            _597 : INT; (*PulpDoser - Spare *)
                            _598 : INT; (*PulpDoser - Spare *)
                            _599 : INT; (*PulpDoser - Spare *)
                            _600 : INT; (*BOTTOM COOLING - Container cooling - Steps from machine inlet to spray activation *)
                            _601 : INT; (*BOTTOM COOLING - Container cooling - Duration in steps of spray active *)
                            _602 : INT; (*BOTTOM COOLING - Container cooling - Spare *)
                            _603 : INT; (*BOTTOM COOLING - Container cooling - Spare *)
                            _604 : INT; (*BOTTOM COOLING - Container cooling - Spare *)
                            _605 : INT; (*FOAMER - Jetter - Steps from machine inlet to Jetter nozzle *)
                            _606 : INT; (*FOAMER - Jetter - Steps from nozzle n°1 to nozzle n°2 *)
                            _607 : INT; (*FOAMER - Foamer - Spare *)
                            _608 : INT; (*FOAMER - Foamer - Spare *)
                            _609 : INT; (*FOAMER - Foamer - Spare *)
                            _610 : INT; (*VBS - Nitrogen doser - Step from machine inlet to Nitrogen dosing position *)
                            _611 : INT; (*VBS - Nitrogen doser - Spare *)
                            _612 : INT; (*VBS - Nitrogen doser - Spare *)
                            _613 : INT; (*VBS - Nitrogen doser - Spare *)
                            _614 : INT; (*VBS - Nitrogen doser - Spare *)
                            _615 : INT; (*SPARE - Spare *)
                            _616 : INT; (*SPARE - Spare *)
                            _617 : INT; (*SPARE - Spare *)
                            _618 : INT; (*SPARE - Spare *)
                            _619 : INT; (*SPARE - Spare *)
                            _620 : INT; (*AROMA DOSER - Dosing Valve Number *)
                            _621 : INT; (*AROMA DOSER - Offset synchro valve in tangent on Doser Valve #1 sensor *)
                            _622 : INT; (*AROMA DOSER - Dosing valve in tangency when drain valve in position *)
                            _623 : INT; (*AROMA DOSER - Doser drain valve position offset [mm]*)
                            _624 : INT; (*SPARE - Spare *)
                            _625 : INT; (*SPARE - Spare *)
                            _626 : INT; (*SPARE - Spare *)
                            _627 : INT; (*SPARE - Spare *)
                            _628 : INT; (*SPARE - Spare *)
                            _629 : INT; (*SPARE - Spare *)
                            _630 : INT; (*SPARE - Spare *)
                            _631 : INT; (*SPARE - Spare *)
                            _632 : INT; (*SPARE - Spare *)
                            _633 : INT; (*SPARE - Spare *)
                            _634 : INT; (*SPARE - Spare *)
                            _635 : INT; (*SPARE - Spare *)
                            _636 : INT; (*SPARE - Spare *)
                            _637 : INT; (*SPARE - Spare *)
                            _638 : INT; (*SPARE - Spare *)
                            _639 : INT; (*SPARE - Spare *)
                            _640 : INT; (*SPARE - Spare *)
                            _641 : INT; (*SPARE - Spare *)
                            _642 : INT; (*SPARE - Spare *)
                            _643 : INT; (*SPARE - Spare *)
                            _644 : INT; (*SPARE - Spare *)
                            _645 : INT; (*SPARE - Spare *)
                            _646 : INT; (*SPARE - Spare *)
                            _647 : INT; (*SPARE - Spare *)
                            _648 : INT; (*SPARE - Spare *)
                            _649 : INT; (*SPARE - Spare *)
                            _650 : INT; (*SPARE - Spare *)
                            _651 : INT; (*SPARE - Spare *)
                            _652 : INT; (*SPARE - Spare *)
                            _653 : INT; (*SPARE - Spare *)
                            _654 : INT; (*SPARE - Spare *)
                            _655 : INT; (*SPARE - Spare *)
                            _656 : INT; (*SPARE - Spare *)
                            _657 : INT; (*SPARE - Spare *)
                            _658 : INT; (*SPARE - Spare *)
                            _659 : INT; (*SPARE - Spare *)
                            _660 : INT; (*SPARE - Spare *)
                            _661 : INT; (*SPARE - Spare *)
                            _662 : INT; (*SPARE - Spare *)
                            _663 : INT; (*SPARE - Spare *)
                            _664 : INT; (*SPARE - Spare *)
                            _665 : INT; (*SPARE - Spare *)
                            _666 : INT; (*SPARE - Spare *)
                            _667 : INT; (*SPARE - Spare *)
                            _668 : INT; (*SPARE - Spare *)
                            _669 : INT; (*SPARE - Spare *)
                            _670 : INT; (*SPARE - Spare *)
                            _671 : INT; (*SPARE - Spare *)
                            _672 : INT; (*SPARE - Spare *)
                            _673 : INT; (*SPARE - Spare *)
                            _674 : INT; (*SPARE - Spare *)
                            _675 : INT; (*SPARE - Spare *)
                            _676 : INT; (*SPARE - Spare *)
                            _677 : INT; (*SPARE - Spare *)
                            _678 : INT; (*SPARE - Spare *)
                            _679 : INT; (*SPARE - Spare *)
                            _680 : INT; (*SPARE - Spare *)
                            _681 : INT; (*SPARE - Spare *)
                            _682 : INT; (*SPARE - Spare *)
                            _683 : INT; (*SPARE - Spare *)
                            _684 : INT; (*SPARE - Spare *)
                            _685 : INT; (*SPARE - Spare *)
                            _686 : INT; (*SPARE - Spare *)
                            _687 : INT; (*SPARE - Spare *)
                            _688 : INT; (*SPARE - Spare *)
                            _689 : INT; (*SPARE - Spare *)
                            _690 : INT; (*SPARE - Spare *)
                            _691 : INT; (*SPARE - Spare *)
                            _692 : INT; (*SPARE - Spare *)
                            _693 : INT; (*SPARE - Spare *)
                            _694 : INT; (*SPARE - Spare *)
                            _695 : INT; (*SPARE - Spare *)
                            _696 : INT; (*SPARE - Spare *)
                            _697 : INT; (*SPARE - Spare *)
                            _698 : INT; (*SPARE - Spare *)
                            _699 : INT; (*SPARE - Spare *)
                            _700 : INT; (*COMBI - Steps from Blower inlet to machine inlet *)
                            _701 : INT; (*COMBI - Steps from Blower inlet to Blower Get Data *)
                            _702 : INT; (*COMBI - Step from Blower inlet to Labeler Get Data *)
                            _703 : INT; (*COMBI - Steps from Labeler ejection to machine inlet *)
                            _704 : INT; (*COMBI - Number of Blower Molds *)
                            _705 : INT; (*SPARE - Step from Combi inlet to Actis Get Data *)
                            _706 : INT; (*SPARE - Syncronization Offset difference with Actis Bypassed *)
                            _707 : INT; (*SPARE - Spare *)
                            _708 : INT; (*SPARE - Spare *)
                            _709 : INT; (*SPARE - Spare *)
                            _710 : INT; (*SPARE - Spare *)
                            _711 : INT; (*SPARE - Spare *)
                            _712 : INT; (*SPARE - Spare *)
                            _713 : INT; (*SPARE - Spare *)
                            _714 : INT; (*SPARE - Spare *)
                            _715 : INT; (*SPARE - Spare *)
                            _716 : INT; (*SPARE - Spare *)
                            _717 : INT; (*SPARE - Spare *)
                            _718 : INT; (*SPARE - Spare *)
                            _719 : INT; (*SPARE - Spare *)
                            _720 : INT; (*SPARE - Spare *)
                            _721 : INT; (*SPARE - Spare *)
                            _722 : INT; (*SPARE - Spare *)
                            _723 : INT; (*SPARE - Spare *)
                            _724 : INT; (*SPARE - Spare *)
                            _725 : INT; (*SPARE - Spare *)
                            _726 : INT; (*SPARE - Spare *)
                            _727 : INT; (*SPARE - Spare *)
                            _728 : INT; (*SPARE - Spare *)
                            _729 : INT; (*SPARE - Spare *)
                            _730 : INT; (*SPARE - Spare *)
                            _731 : INT; (*SPARE - Spare *)
                            _732 : INT; (*SPARE - Spare *)
                            _733 : INT; (*SPARE - Spare *)
                            _734 : INT; (*SPARE - Spare *)
                            _735 : INT; (*SPARE - Spare *)
                            _736 : INT; (*SPARE - Spare *)
                            _737 : INT; (*SPARE - Spare *)
                            _738 : INT; (*SPARE - Spare *)
                            _739 : INT; (*SPARE - Spare *)
                            _740 : INT; (*SPARE - Spare *)
                            _741 : INT; (*SPARE - Spare *)
                            _742 : INT; (*SPARE - Spare *)
                            _743 : INT; (*SPARE - Spare *)
                            _744 : INT; (*SPARE - Spare *)
                            _745 : INT; (*SPARE - Spare *)
                            _746 : INT; (*SPARE - Spare *)
                            _747 : INT; (*SPARE - Spare *)
                            _748 : INT; (*SPARE - Spare *)
                            _749 : INT; (*SPARE - Spare *)
                            _750 : INT; (*SPARE - Spare *)
                            _751 : INT; (*SPARE - Spare *)
                            _752 : INT; (*SPARE - Spare *)
                            _753 : INT; (*SPARE - Spare *)
                            _754 : INT; (*SPARE - Spare *)
                            _755 : INT; (*SPARE - Spare *)
                            _756 : INT; (*SPARE - Spare *)
                            _757 : INT; (*SPARE - Spare *)
                            _758 : INT; (*SPARE - Spare *)
                            _759 : INT; (*SPARE - Spare *)
                            _760 : INT; (*SPARE - Spare *)
                            _761 : INT; (*SPARE - Spare *)
                            _762 : INT; (*SPARE - Spare *)
                            _763 : INT; (*SPARE - Spare *)
                            _764 : INT; (*SPARE - Spare *)
                            _765 : INT; (*SPARE - Spare *)
                            _766 : INT; (*SPARE - Spare *)
                            _767 : INT; (*SPARE - Spare *)
                            _768 : INT; (*SPARE - Spare *)
                            _769 : INT; (*SPARE - Spare *)
                            _770 : INT; (*SPARE - Spare *)
                            _771 : INT; (*SPARE - Spare *)
                            _772 : INT; (*SPARE - Spare *)
                            _773 : INT; (*SPARE - Spare *)
                            _774 : INT; (*SPARE - Spare *)
                            _775 : INT; (*SPARE - Spare *)
                            _776 : INT; (*SPARE - Spare *)
                            _777 : INT; (*SPARE - Spare *)
                            _778 : INT; (*SPARE - Spare *)
                            _779 : INT; (*SPARE - Spare *)
                            _780 : INT; (*SPARE - Spare *)
                            _781 : INT; (*SPARE - Spare *)
                            _782 : INT; (*SPARE - Spare *)
                            _783 : INT; (*SPARE - Spare *)
                            _784 : INT; (*SPARE - Spare *)
                            _785 : INT; (*SPARE - Spare *)
                            _786 : INT; (*SPARE - Spare *)
                            _787 : INT; (*SPARE - Spare *)
                            _788 : INT; (*SPARE - Spare *)
                            _789 : INT; (*SPARE - Spare *)
                            _790 : INT; (*SPARE - Spare *)
                            _791 : INT; (*SPARE - Spare *)
                            _792 : INT; (*SPARE - Spare *)
                            _793 : INT; (*SPARE - Spare *)
                            _794 : INT; (*SPARE - Spare *)
                            _795 : INT; (*SPARE - Spare *)
                            _796 : INT; (*SPARE - Spare *)
                            _797 : INT; (*SPARE - Spare *)
                            _798 : INT; (*SPARE - Spare *)
                            _799 : INT; (*SPARE - Spare *)
                            _800 : INT; (*SEAMER - Heads Number *)
                            _801 : INT; (*SPARE - Spare *)
                            _802 : INT; (*SPARE - Spare *)
                            _803 : INT; (*SPARE - Spare *)
                            _804 : INT; (*SPARE - Spare *)
                            _805 : INT; (*SPARE - Spare *)
                            _806 : INT; (*SPARE - Spare *)
                            _807 : INT; (*SPARE - Spare *)
                            _808 : INT; (*SPARE - Spare *)
                            _809 : INT; (*SPARE - Spare *)
                            _810 : INT; (*SPARE - Spare *)
                            _811 : INT; (*SPARE - Spare *)
                            _812 : INT; (*SPARE - Spare *)
                            _813 : INT; (*SPARE - Spare *)
                            _814 : INT; (*SPARE - Spare *)
                            _815 : INT; (*SPARE - Spare *)
                            _816 : INT; (*SPARE - Spare *)
                            _817 : INT; (*SPARE - Spare *)
                            _818 : INT; (*SPARE - Spare *)
                            _819 : INT; (*SPARE - Spare *)
                            _820 : INT; (*SPARE - Spare *)
                            _821 : INT; (*SPARE - Spare *)
                            _822 : INT; (*SPARE - Spare *)
                            _823 : INT; (*SPARE - Spare *)
                            _824 : INT; (*SPARE - Spare *)
                            _825 : INT; (*SPARE - Spare *)
                            _826 : INT; (*SPARE - Spare *)
                            _827 : INT; (*SPARE - Spare *)
                            _828 : INT; (*SPARE - Spare *)
                            _829 : INT; (*SPARE - Spare *)
                            _830 : INT; (*SPARE - Spare *)
                            _831 : INT; (*SPARE - Spare *)
                            _832 : INT; (*SPARE - Spare *)
                            _833 : INT; (*SPARE - Spare *)
                            _834 : INT; (*SPARE - Spare *)
                            _835 : INT; (*SPARE - Spare *)
                            _836 : INT; (*SPARE - Spare *)
                            _837 : INT; (*SPARE - Spare *)
                            _838 : INT; (*SPARE - Spare *)
                            _839 : INT; (*SPARE - Spare *)
                            _840 : INT; (*SPARE - Spare *)
                            _841 : INT; (*SPARE - Spare *)
                            _842 : INT; (*SPARE - Spare *)
                            _843 : INT; (*SPARE - Spare *)
                            _844 : INT; (*SPARE - Spare *)
                            _845 : INT; (*SPARE - Spare *)
                            _846 : INT; (*SPARE - Spare *)
                            _847 : INT; (*SPARE - Spare *)
                            _848 : INT; (*SPARE - Spare *)
                            _849 : INT; (*SPARE - Spare *)
                            _850 : INT; (*SPARE - Spare *)
                            _851 : INT; (*SPARE - Spare *)
                            _852 : INT; (*SPARE - Spare *)
                            _853 : INT; (*SPARE - Spare *)
                            _854 : INT; (*SPARE - Spare *)
                            _855 : INT; (*SPARE - Spare *)
                            _856 : INT; (*SPARE - Spare *)
                            _857 : INT; (*SPARE - Spare *)
                            _858 : INT; (*SPARE - Spare *)
                            _859 : INT; (*SPARE - Spare *)
                            _860 : INT; (*SPARE - Spare *)
                            _861 : INT; (*SPARE - Spare *)
                            _862 : INT; (*SPARE - Spare *)
                            _863 : INT; (*SPARE - Spare *)
                            _864 : INT; (*SPARE - Spare *)
                            _865 : INT; (*SPARE - Spare *)
                            _866 : INT; (*SPARE - Spare *)
                            _867 : INT; (*SPARE - Spare *)
                            _868 : INT; (*SPARE - Spare *)
                            _869 : INT; (*SPARE - Spare *)
                            _870 : INT; (*SPARE - Spare *)
                            _871 : INT; (*SPARE - Spare *)
                            _872 : INT; (*SPARE - Spare *)
                            _873 : INT; (*SPARE - Spare *)
                            _874 : INT; (*SPARE - Spare *)
                            _875 : INT; (*SPARE - Spare *)
                            _876 : INT; (*SPARE - Spare *)
                            _877 : INT; (*SPARE - Spare *)
                            _878 : INT; (*SPARE - Spare *)
                            _879 : INT; (*SPARE - Spare *)
                            _880 : INT; (*SPARE - Spare *)
                            _881 : INT; (*SPARE - Spare *)
                            _882 : INT; (*SPARE - Spare *)
                            _883 : INT; (*SPARE - Spare *)
                            _884 : INT; (*SPARE - Spare *)
                            _885 : INT; (*SPARE - Spare *)
                            _886 : INT; (*SPARE - Spare *)
                            _887 : INT; (*SPARE - Spare *)
                            _888 : INT; (*SPARE - Spare *)
                            _889 : INT; (*SPARE - Spare *)
                            _890 : INT; (*SPARE - Spare *)
                            _891 : INT; (*SPARE - Spare *)
                            _892 : INT; (*SPARE - Spare *)
                            _893 : INT; (*SPARE - Spare *)
                            _894 : INT; (*SPARE - Spare *)
                            _895 : INT; (*SPARE - Spare *)
                            _896 : INT; (*SPARE - Spare *)
                            _897 : INT; (*SPARE - Spare *)
                            _898 : INT; (*SPARE - Spare *)
                            _899 : INT; (*SPARE - Spare *)
                            _900 : INT; (*SPARE - Spare *)
                            _901 : INT; (*SPARE - Spare *)
                            _902 : INT; (*SPARE - Spare *)
                            _903 : INT; (*SPARE - Spare *)
                            _904 : INT; (*SPARE - Spare *)
                            _905 : INT; (*SPARE - Spare *)
                            _906 : INT; (*SPARE - Spare *)
                            _907 : INT; (*SPARE - Spare *)
                            _908 : INT; (*SPARE - Spare *)
                            _909 : INT; (*SPARE - Spare *)
                            _910 : INT; (*SPARE - Spare *)
                            _911 : INT; (*SPARE - Spare *)
                            _912 : INT; (*SPARE - Spare *)
                            _913 : INT; (*SPARE - Spare *)
                            _914 : INT; (*SPARE - Spare *)
                            _915 : INT; (*SPARE - Spare *)
                            _916 : INT; (*SPARE - Spare *)
                            _917 : INT; (*SPARE - Spare *)
                            _918 : INT; (*SPARE - Spare *)
                            _919 : INT; (*SPARE - Spare *)
                            _920 : INT; (*SPARE - Spare *)
                            _921 : INT; (*SPARE - Spare *)
                            _922 : INT; (*SPARE - Spare *)
                            _923 : INT; (*SPARE - Spare *)
                            _924 : INT; (*SPARE - Spare *)
                            _925 : INT; (*SPARE - Spare *)
                            _926 : INT; (*SPARE - Spare *)
                            _927 : INT; (*SPARE - Spare *)
                            _928 : INT; (*SPARE - Spare *)
                            _929 : INT; (*SPARE - Spare *)
                            _930 : INT; (*SPARE - Spare *)
                            _931 : INT; (*SPARE - Spare *)
                            _932 : INT; (*SPARE - Spare *)
                            _933 : INT; (*SPARE - Spare *)
                            _934 : INT; (*SPARE - Spare *)
                            _935 : INT; (*SPARE - Spare *)
                            _936 : INT; (*SPARE - Spare *)
                            _937 : INT; (*SPARE - Spare *)
                            _938 : INT; (*SPARE - Spare *)
                            _939 : INT; (*SPARE - Spare *)
                            _940 : INT; (*SPARE - Spare *)
                            _941 : INT; (*SPARE - Spare *)
                            _942 : INT; (*SPARE - Spare *)
                            _943 : INT; (*SPARE - Spare *)
                            _944 : INT; (*SPARE - Spare *)
                            _945 : INT; (*SPARE - Spare *)
                            _946 : INT; (*SPARE - Spare *)
                            _947 : INT; (*SPARE - Spare *)
                            _948 : INT; (*SPARE - Spare *)
                            _949 : INT; (*SPARE - Spare *)
                            _950 : INT; (*SPARE - Spare *)
                            _951 : INT; (*SPARE - Spare *)
                            _952 : INT; (*SPARE - Spare *)
                            _953 : INT; (*SPARE - Spare *)
                            _954 : INT; (*SPARE - Spare *)
                            _955 : INT; (*SPARE - Spare *)
                            _956 : INT; (*SPARE - Spare *)
                            _957 : INT; (*SPARE - Spare *)
                            _958 : INT; (*SPARE - Spare *)
                            _959 : INT; (*SPARE - Spare *)
                            _960 : INT; (*SPARE - Spare *)
                            _961 : INT; (*SPARE - Spare *)
                            _962 : INT; (*SPARE - Spare *)
                            _963 : INT; (*SPARE - Spare *)
                            _964 : INT; (*SPARE - Spare *)
                            _965 : INT; (*SPARE - Spare *)
                            _966 : INT; (*SPARE - Spare *)
                            _967 : INT; (*SPARE - Spare *)
                            _968 : INT; (*SPARE - Spare *)
                            _969 : INT; (*SPARE - Spare *)
                            _970 : INT; (*SPARE - Spare *)
                            _971 : INT; (*SPARE - Spare *)
                            _972 : INT; (*SPARE - Spare *)
                            _973 : INT; (*SPARE - Spare *)
                            _974 : INT; (*SPARE - Spare *)
                            _975 : INT; (*SPARE - Spare *)
                            _976 : INT; (*SPARE - Spare *)
                            _977 : INT; (*SPARE - Spare *)
                            _978 : INT; (*SPARE - Spare *)
                            _979 : INT; (*SPARE - Spare *)
                            _980 : INT; (*SPARE - Spare *)
                            _981 : INT; (*SPARE - Spare *)
                            _982 : INT; (*SPARE - Spare *)
                            _983 : INT; (*SPARE - Spare *)
                            _984 : INT; (*SPARE - Spare *)
                            _985 : INT; (*SPARE - Spare *)
                            _986 : INT; (*SPARE - Spare *)
                            _987 : INT; (*SPARE - Spare *)
                            _988 : INT; (*SPARE - Spare *)
                            _989 : INT; (*SPARE - Spare *)
                            _990 : INT; (*SPARE - Spare *)
                            _991 : INT; (*SPARE - Spare *)
                            _992 : INT; (*SPARE - Spare *)
                            _993 : INT; (*SPARE - Spare *)
                            _994 : INT; (*SPARE - Spare *)
                            _995 : INT; (*SPARE - Spare *)
                            _996 : INT; (*SPARE - Spare *)
                            _997 : INT; (*SPARE - Spare *)
                            _998 : INT; (*SPARE - Spare *)
                            _999 : INT; (*SPARE - Spare *)
        END_STRUCT;
END_TYPE
