(*HMI_PAM_A1 Initialization Action for Filler PLC*)
(*Author = ????*)
(*DB Version : 0.00*)
(*File Version : 2.88*)

ACTION HMI_PAM_A1_Init :
        HMI_PAM_A1._000 := 0;
        HMI_PAM_A1._001 := 0;
        HMI_PAM_A1._002 := 0;
        HMI_PAM_A1._005 := 0;
        HMI_PAM_A1._006 := 0;
        HMI_PAM_A1._007 := 0;
        HMI_PAM_A1._010 := 0;
        HMI_PAM_A1._011 := 0;
        HMI_PAM_A1._012 := 0;
        HMI_PAM_A1._015 := 0;
        HMI_PAM_A1._016 := 0;
        HMI_PAM_A1._017 := 0;
        HMI_PAM_A1._020 := 0;
        HMI_PAM_A1._021 := 0;
        HMI_PAM_A1._022 := 0;
        HMI_PAM_A1._025 := 0;
        HMI_PAM_A1._026 := 0;
        HMI_PAM_A1._027 := 0;
        HMI_PAM_A1._030 := 0;
        HMI_PAM_A1._031 := 0;
        HMI_PAM_A1._032 := 0;
        HMI_PAM_A1._035 := 0;
        HMI_PAM_A1._036 := 0;
        HMI_PAM_A1._037 := 0;
        HMI_PAM_A1._040 := 0;
        HMI_PAM_A1._041 := 0;
        HMI_PAM_A1._042 := 0;
        HMI_PAM_A1._045 := 0;
        HMI_PAM_A1._046 := 0;
        HMI_PAM_A1._047 := 0;
        HMI_PAM_A1._050 := 0;
        HMI_PAM_A1._051 := 0;
        HMI_PAM_A1._052 := 0;
        HMI_PAM_A1._055 := 0;
        HMI_PAM_A1._056 := 0;
        HMI_PAM_A1._057 := 0;
        HMI_PAM_A1._060 := 0;
        HMI_PAM_A1._061 := 0;
        HMI_PAM_A1._062 := 0;
END_ACTION
