(*HMI_PAM_B1 Initialization Action for Filler PLC*)
(*Author = ????*)
(*DB Version : 0.00*)
(*File Version : 3,17*)

ACTION HMI_PAM_B1_Init :
        HMI_PAM_B1._000 := 0;
        HMI_PAM_B1._001 := 40;
        HMI_PAM_B1._005 := 1;
        HMI_PAM_B1._006 := 40;
        HMI_PAM_B1._010 := 0;
        HMI_PAM_B1._011 := 40;
        HMI_PAM_B1._015 := 1;
        HMI_PAM_B1._016 := 40;
        HMI_PAM_B1._020 := 0;
        HMI_PAM_B1._021 := 40;
        HMI_PAM_B1._025 := 1;
        HMI_PAM_B1._026 := 40;
        HMI_PAM_B1._030 := 0;
        HMI_PAM_B1._031 := 40;
        HMI_PAM_B1._035 := 1;
        HMI_PAM_B1._036 := 40;
        HMI_PAM_B1._040 := 0;
        HMI_PAM_B1._041 := 40;
        HMI_PAM_B1._045 := 1;
        HMI_PAM_B1._046 := 40;
        HMI_PAM_B1._050 := 1;
        HMI_PAM_B1._051 := 40;
        HMI_PAM_B1._500 := 5;
        HMI_PAM_B1._501 := 60;
        HMI_PAM_B1._505 := 0;
        HMI_PAM_B1._506 := 100;
        HMI_PAM_B1._510 := 0;
        HMI_PAM_B1._511 := 100;
        HMI_PAM_B1._515 := 0;
        HMI_PAM_B1._516 := 100;
        HMI_PAM_B1._520 := 0;
        HMI_PAM_B1._521 := 100;
        HMI_PAM_B1._525 := 0;
        HMI_PAM_B1._526 := 100;
        HMI_PAM_B1._530 := 0;
        HMI_PAM_B1._531 := 100;
        HMI_PAM_B1._535 := 0;
        HMI_PAM_B1._536 := 100;
        HMI_PAM_B1._540 := 0;
        HMI_PAM_B1._541 := 100;
        HMI_PAM_B1._545 := 0;
        HMI_PAM_B1._546 := 100;
END_ACTION
