ACTION HMI_CSR_Loading:
	HMI_CSR_PB;
	HMI_CSR_SS2P;
	HMI_CSR_SS3P;
	HMI_LTK;
	HMI_CSR_State;
	HMI_CSR_SCU;
	HMI_CSR_Column;
	HMI_CSR_TnkLinftingMotor;
	HMI_CSR_Data;
	HMI_2808M1;(*master nuovo*)
	HMI_204CPC;(*master nuovo*)
	HMI_2809M2;(*master nuovo*)
	HMI_YV26;(*master nuovo*)
	HMI_YV39;(*master nuovo*)
	HMI_SQ26;(*master nuovo*)
	HMI_SQ45A2;(*master nuovo*)
	HMI_SQ45A1;(*master nuovo*)
	HMI_SQ70;(*master nuovo*)
	HMI_SQ5;(*master nuovo*)
	HMI_SQ6;(*master nuovo*)
	HMI_CSR_SikoActualPosition;//V1.61
	HMI_CSR_SikoConveyorData;//V1.61
	HMI_CSR_SikoGuideData;//V1.61

END_ACTION

