ACTION HMI_OPS_Loading:
	HMI_OPS_Zone;
	HMI_OPS_Door;
	HMI_OPS_DoorCabinet;//V1.3
	HMI_OPS_DoorCabinet_Visibility;//V4.A.A.1.7.0
	HMI_OPS_Euchner;//V1.3
	HMI_OPS_SafetySwitch;//V4.A.A.1.7.1
	HMI_OPS_Emergency;
	HMI_OPS_EmergencyBlower;
	HMI_OPS_EmergencyLabeller;
	HMI_OPS_EmergencyConveyor;
	HMI_OPS_EmergencyNitrodoser;
	HMI_OPS_EmergencyCapsFeeder;
	HMI_OPS_EmergencyCrownFeeder;
	HMI_OPS_Jog;
	HMI_OPS_JogFwExt;//vrma106
	HMI_OPS_ModeSelectorAdjustment;
	HMI_OPS_ModeSelectorJog; //V4.A.A.1.6.13
	HMI_OPS_ModeSelectorAuto; //V4.A.A.1.6.13
	HMI_OPS_GateDoor;
	HMI_OPS_SafetyWidget;
	HMI_OPS_Pictogram;
	HMI_OPS_PB;
	HMI_OPS_SS2P;//V4.A.A.1.6.12h
	HMI_OPS_ZoneComboString;
	HMI_OPS_Cfg;
	HMI_OPS_BufferDoor;
	HMI_OPS_BufferZone;
	HMI_207EVF;//V4.A.A.1.6.12
	HMI_209EVF;
	HMI_208CPF;//V4.A.A.1.6.12
	HMI_208DSFX;//V4.A.A.1.6.12
	HMI_208DSFY;//V4.A.A.1.6.12	
	HMI_209DSFX;//V4.A.A.1.6.12	
	HMI_209DSFY;//V4.A.A.1.6.12	
END_ACTION
