ACTION HMI_DMC_Loading:
	HMI_DMC_SS2P;
	HMI_DMC_PB;//v999
	HMI_DMC_StepActual; // NOT USED
	HMI_DMC_State;
	HMI_DMC_Number;
	HMI_DMC_InsertionSensor;
	HMI_DMC_InsertionPiston;
	HMI_DMC_Installed;
	HMI_DMC_Visualization;
	HMI_205RVF;
	HMI_DMC_OkFromOperatorCheck;
	HMI_DMC_AbortFromOperatorCheck;
	HMI_DMC_ManModeStatus;//v999
	HMI_DMC_AutoModeStatus;
	HMI_DMC_TankHeightPosOk;//
	HMI_DMC_Sector1LastValveNum;//v999
	HMI_DMC_Sector2FirstValveNum;//v999
	HMI_DMC_Sector2LastValveNum;//v999
END_ACTION